### PR TITLE
docs: improved PR template

### LINKED ISSUE #1529: docs: Improve PR template
The current PR template (as shown below) isn't much detailed and misses out on certain important points. It is quite useful to make sure to follow a standard process for every pull request and to have a to-do list for the author to check before requesting a review (which the current template lacks). 

I'd like to work on its improvement.

### PR DESCRIPTION
**Pull request by abhilipsasahoo03**
Signed-off-by: Abhilipsa Sahoo <abhilipsasahoo03@gmail.com>

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Improved PR template to include tests and configurations, note for reviewers, check list, and other sections. 

- **Why was this change needed?** (You can also link to an open issue here)
Fixes #1529

### CODE REVIEW

**Comment by abhilipsasahoo03** [comment]
@scopsy @davidsoderberg @ainouzgali could you please take a look?

**Comment by BiswaViraj** [comment]
Thank you for the PR @abhilipsasahoo03 ,

@novuhq/novu-team, What do you think about this new PR template?
It does miss out on the what and why aspects of the side discussed during our retreat meeting.
Also, wdyt about the added checklists? are those needed?

**Comment by abhilipsasahoo03** [comment]
Hi @davidsoderberg could you please look into this?

**Comment by davidsoderberg** [comment]
For me personally I think it is to much info to fill in... Specially for the Novu team that creates a lot of PRs...

**Comment by abhilipsasahoo03** [comment]
> For me personally I think it is to much info to fill in... Specially for the Novu team that creates a lot of PRs...

How about we remove the checklist? Sections other than description part are optional anyway right?

**Comment by davidsoderberg** [comment]
Like most of those stuff either the Github actions tests or eslint fixes automatic... The only thing that we need to really check is breaking changes and that tests exists. But not in all PR we need to check that even. We recently changed the PR template to be easier to fill in I would rather add some info text in the PR template that we expect tests for larger changes and breaking changes can be hard to figure out if you are not a member of the Novu team sometimes... 
It should take as less time as possible to contribute to make it even more fun to contribute :)

**Comment by abhilipsasahoo03** [comment]
> Like most of those stuff either the Github actions tests or eslint fixes automatic... The only thing that we need to really check is breaking changes and that tests exists. But not in all PR we need to check that even. We recently changed the PR template to be easier to fill in I would rather add some info text in the PR template that we expect tests for larger changes and breaking changes can be hard to figure out if you are not a member of the Novu team sometimes... 
> It should take as less time as possible to contribute to make it even more fun to contribute :)

That is true. I suggested this template and incorporated checklist into it from the point of view of someone who's not in the Novu team, rather a new contributor, so this template would act as a framework for baseline standard of informational quality and organizational rigor. I hope it makes sense.

**Comment by scopsy** [comment]
@abhilipsasahoo03 although I really like this template and will use it in my personal project, just as @davidsoderberg mentioned it will create quite a lot of overhead for a lot of our contributions outside of hacktoberfest. Maybe in the future we might be able to specify contribution templates based on first time contributors.

For now I will close this PR, but just wanted to again thank you for your consideration of adding this, as I think make sense. But in our particular case it will just create too much overhead. 🙏

**Comment by abhilipsasahoo03** [comment]
> @abhilipsasahoo03 although I really like this template and will use it in my personal project, just as @davidsoderberg mentioned it will create quite a lot of overhead for a lot of our contributions outside of hacktoberfest. Maybe in the future we might be able to specify contribution templates based on first time contributors.
> 
> For now I will close this PR, but just wanted to again thank you for your consideration of adding this, as I think make sense. But in our particular case it will just create too much overhead. 🙏

I absolutely understand your concern. :)

**Pull request closed without merging**
