### PR TITLE
fix: no return in map function

### PR DESCRIPTION
**Pull request by ShashwatAgrawal20**
### What change does this PR introduce? 
This PR solves the issue of no return statement in the callback function of the array method.

just converted the map to the forEach loop. 

### Why was this change needed?
The array has several methods for filtering, mapping, and folding. If we forget to write a return statement in a callback of those, it's probably a mistake.

### CODE REVIEW

**Review by scopsy — APPROVED** [review]
Wonder if there is an eslint rule for this :o

**Comment by BiswaViraj** [comment]
@scopsy @ShashwatAgrawal20 
I think this eslint rule will work 
https://eslint.org/docs/latest/rules/array-callback-return

**Comment by ShashwatAgrawal20** [comment]
> @scopsy @ShashwatAgrawal20 I think this eslint rule will work https://eslint.org/docs/latest/rules/array-callback-return

can you please explain some more?

**Comment by ShashwatAgrawal20** [comment]
@scopsy can you guide me on what changes are needed to be met?

**Comment by scopsy** [comment]
@ShashwatAgrawal20 no need to implement the eslint rule, was just thinking out loud :)

Could you please merge latest next changes from upstream to here? Seems like some tests are failing.

**Comment by ShashwatAgrawal20** [comment]
@scopsy done

**Comment by ainouzgali** [comment]
Thanks @ShashwatAgrawal20 :)

**Pull request merged**
