### PR TITLE
feat: added sms-to sms provider

### LINKED ISSUE #4339: [NV-2942] 🚀 Feature: Add SMS.to sms provider
### 🔖 Feature description

Use the [sms.to sms documentation](https://developers.sms.to/#3a12f9ae-8afa-4d15-a3c5-4895c3a14778) to add a new sms provider by following [Novu's new provider guide](https://docs.novu.co/community/add-a-new-provider#how-to-add-a-new-provider)

### 🎤 Why is this feature needed ?

To add more providers to the community

### ✌️ How do you aim to achieve this?

Community contributions

### 🔄️ Additional Information

_No response_

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2942](https://linear.app/novu/issue/NV-2942/🚀-feature-add-smsto-sms-provider)</sub>

### PR DESCRIPTION
**Pull request by rvikunwar**
### What change does this PR introduce?

Added New provider "SMSto" to sms providers

### Why was this change needed?

This change Closes #4339 

### Other information (Screenshots)

smsto

### CODE REVIEW

**Comment by davidsoderberg** [comment]
@rvikunwar I am wondering if sms-to have a logo for dark mode because half of the logo is hard to see as it is on your screenshot?

**Comment by rvikunwar** [comment]
> @rvikunwar I am wondering if sms-to have a logo for dark mode because half of the logo is hard to see as it is on your screenshot?

@davidsoderberg I think it can be due to the reason that I have highlighted sms to logo in above screenshot, you can check this screenshot and let me know if you still observing the same issue
sms

**Comment by davidsoderberg** [comment]
> > @rvikunwar I am wondering if sms-to have a logo for dark mode because half of the logo is hard to see as it is on your screenshot?
> 
> @davidsoderberg I think it can be due to the reason that I have highlighted sms to logo in above screenshot, you can check this screenshot and let me know if you still observing the same issue sms

Hm would happily get @scopsy or @LetItRock eyes on this because I still think it is a bit dark.

**Comment by davidsoderberg** [comment]
Also could you check if it works with the new multi provider config to enable it change the fallback to true in `/apps/web/src/hooks/useFeatureFlags.ts` on line 34.

**Comment by davidsoderberg** [comment]
> > Also could you check if it works with the new multi provider config to enable it change the fallback to true in `/apps/web/src/hooks/useFeatureFlags.ts` on line 34.
> 
> sure I can check but this Issue is closed, I don't know why Should I continue or leave it as it is.

I will check why it was closed as well, but I think it can be a sync issue between Linear (we use it for the team internal) and Github.

**Comment by rvikunwar** [comment]
> > > Also could you check if it works with the new multi provider config to enable it change the fallback to true in `/apps/web/src/hooks/useFeatureFlags.ts` on line 34.
> > 
> > 
> > sure I can check but this Issue is closed, I don't know why Should I continue or leave it as it is.
> 
> I will check why it was closed as well, but I think it can be a sync issue between Linear (we use it for the team internal) and Github.

sure thanks

**Comment by Cliftonz** [comment]
https://github.com/novuhq/novu/issues/4339

**Comment by rvikunwar** [comment]
@davidsoderberg I have updated the icons for light and dark mode 

sms-to-dark
sms-to-light
can you check and let me know if there are fixes that needs to be done.

**Comment by hhh7000** [comment]
```
B****
```[[__]()]()

**Comment by davidsoderberg** [comment]
Can you please send some new screenshots? the logos looks good on its own but it is easier to see them in their context as well :)

**Comment by scopsy** [comment]
Closing due to inactivity, feel free to reopen 🙏

**Pull request closed without merging**
