### PR TITLE
fix(@novu/fcm): use message instead of body for data-type notifications

### PR DESCRIPTION
**Pull request by cherfia**
### What change does this PR introduce?

Fixed the bug reported https://github.com/novuhq/novu/issues/4639 by including the `message` property in the `data` sent by the FCM provider, aligning with [Expo documentation](https://docs.expo.dev/push-notifications/sending-notifications-custom/).

### Why was this change needed?
The notifications were displaying only the titles and not rendering the notification message body.

### Other information
While the `body` property is not required for data-type notifications, it has been retained for backward compatibility to support users who already rely on it.

### CODE REVIEW

**Comment by p-fernandez** [comment]
Thanks for your contribution. 
You will need to update the tests based on the change you have done.

**Comment by cherfia** [comment]
@p-fernandez I have updated [fcm.provider.spec.ts](https://github.com/novuhq/novu/pull/4652/files#diff-b3fcdc39b9827c10db8e1dbc330b523a52fc0fc7eba11bef3c9a3da29f7fd6fb) to include `message` property and `NX Successfully ran target test for project @novu/fcm`

**Review by p-fernandez — APPROVED** [review]
Thank you for your contribution.
🌟

**Comment by cherfia** [comment]
Thanks! I'm committed to ongoing contributions to Novu as it's integral part of our open-source solution ⭐

**Pull request merged**
