### PR TITLE
docs: add machine setup from novu handbook

### PR DESCRIPTION
**Pull request by iampearceman**

### CODE REVIEW

**Comment by iampearceman** [comment]
After discussing the matter with @Abobos and @davidsoderberg  we thought it could useful to have the machine setup from Notion on our github as well

**Comment by davidsoderberg** [comment]
One of my question is where this info should be Notion or Github? 
Having the same info in two places seems hard to maintain...

**Comment by scopsy** [comment]
Aggree with @davidsoderberg we should only have one portion of this. I would separate the project related and global stuff. Project related things can be in our docs. Non project related nice-haves such as zsh and etc, not sure we need to have them in the projects docs.

**Comment by scopsy** [comment]
@iampearceman moved this as part of running Novu Locally in the docs section, so closing this for now here.

**Pull request closed without merging**
