### PR TITLE
Docs: Quickstart guide on Getting started with Go

### PR DESCRIPTION
**Pull request by olumidayy**
### What change does this PR introduce?

This PR introduce the Getting started with Go Quickstart.
As this quickstart guide is not available from the [quickstart section](https://docs.novu.co/overview/quickstart/general-quickstart/)

Why was this change needed?
Closes https://github.com/novuhq/go-novu/issues/20

### CODE REVIEW

**Comment by unicodeveloper** [comment]
Hi @olumidayy thank you for doing this!

Please can you resubmit this PR to the `main` branch. It's documentation that we'll need to go live as soon as possible once we are done reviewing. Thanks 🙏🏿

**Review by unicodeveloper — COMMENTED** [review]
Did you create a go quickstart repo? If so, please can I see it?

**Comment by olumidayy** [comment]
> Hi @olumidayy thank you for doing this!
> 
> Please can you resubmit this PR to the `main` branch. It's documentation that we'll need to go live as soon as possible once we are done reviewing. Thanks 🙏🏿

Alright I'll do that

**Comment by olumidayy** [comment]
> Did you create a go quickstart repo? If so, please can I see it?

No I didn't, @unicodeveloper. Should I do that?

**Comment by olumidayy** [comment]
I've moved this here https://github.com/novuhq/novu/pull/3842

**Pull request closed without merging**
