### PR TITLE
Create CODE_OF_CONDUCT.md 2.0 for the repository

### PR DESCRIPTION
**Pull request by Rutam21**
What kind of change does this PR introduce?
This PR adds the Github Code_Of_Conduct 2.0 for the Contributors to the repository.

Is there an open issue for this?
This issue fixes https://github.com/novuhq/novu/issues/1037

### CODE REVIEW

**Comment by Rutam21** [comment]
@scopsy @davidsoderberg Please review the Code of Conduct file for this repository that I have added. FYI, this is the version 2.0 template made available by Github whereas the Novu Docs site currently uses version 1.4. So, if you suggest, we can also update the Conduct on the Docs site to 2.0. Thanks.

**Comment by scopsy** [comment]
Thank you Rutam, do you mind also updating the docs.novu.co page for it?

**Comment by Rutam21** [comment]
@scopsy Yeah, sure. I will update the docs site as well. Thanks.

**Comment by scopsy** [comment]
Oh looks like this was deleted :( Is it by mistake?

**Comment by Rutam21** [comment]
I have added new PRs already. 🙂

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Tags:** Reusable

**Comment by Rutam21** [comment]
I have added new PRs already. 🙂

**Pull request closed without merging**
