### PR TITLE
fix(button-variables): button link variables not showing to user in email message editor

### LINKED ISSUE #4253: [NV-2396] Link variable in button not shown to user
## Reproduction Steps
Variables in buttons are not shown in the variables manager. 
If added to payload works as expected. Does show in the trigger snippet.

1. Create a workflow.
2. Add the Email step to the workflow.
3. Open the editor.
4. Click "Plus" button and choose "Add button".
5. Add any new variable to the button link.

image

## Definition of Done
- The variables from the button link should be visible in the Step Variables

### PR DESCRIPTION
**Pull request by rockingrohit9639**
### What change does this PR introduce?

This PR resolves the issue that variables inside the button URL do not appear in Variables Manager.
Thank you @LetItRock for helping me out.

### Why was this change needed?

Closes #4253 

### Other information (Screenshots)

https://github.com/novuhq/novu/assets/40729749/7d4f4c6c-ff1d-4de9-a7d8-feff75fd83cb

https://github.com/novuhq/novu/assets/40729749/0dbedb0f-84e8-4124-95dc-6127282f6f7d

### CODE REVIEW

**Comment by davidsoderberg** [comment]
Would be great if you could provide a screenshot of the result :)

**Comment by rockingrohit9639** [comment]
> Would be great if you could provide a screenshot of the result :)

I have added a video in description.

**Review by davidsoderberg — APPROVED** [review]

**Comment by davidsoderberg** [comment]
Could you make a video of the exact usecase in the issue, because updating an existing button looks good :)

**Comment by rockingrohit9639** [comment]
> Could you make a video of the exact usecase in the issue, because updating an existing button looks good :)

I have added another video.

**Comment by davidsoderberg** [comment]
Alright will do some small tests of my own before merging but looks good :)

**Comment by davidsoderberg** [comment]
After my small test it seems to work as expected, thanks for your contribution 🥳

**Comment by rockingrohit9639** [comment]
> After my small test it seems to work as expected, thanks for your contribution 🥳

Thank you very much @davidsoderberg

**Pull request merged**
