### PR TITLE
feat: add pusher beams provider

### PR DESCRIPTION
**Pull request by im-perativa**
### What change does this PR introduce?

Add Pusher Beam as a Push Provider

### Why was this change needed?

Closes https://github.com/novuhq/novu/issues/4634

### Other information (Screenshots)

image

### CODE REVIEW

**Comment by Cliftonz** [comment]
@im-perativa looks like there is some conflics that need to be resolved

**Comment by im-perativa** [comment]
@Cliftonz done 👍

**Comment by Cliftonz** [comment]
@im-perativa looks like there is some conflicts that need to be resolved, this may happen a few more times as we are merging alot of providers right now. 
Apologizes, please be patient with us.

**Comment by im-perativa** [comment]
@Cliftonz done

**Review by Cliftonz — APPROVED** [review]

**Comment by im-perativa** [comment]
@Cliftonz yes, i believe it's because the official [Node SDK](https://www.npmjs.com/package/@pusher/push-notifications-server) from Pusher as metioned on the official [docs](https://pusher.com/docs/beams/reference/server-sdk-node/) still use `jsonwebtoken@8.5.1` package that triggers the alarm.

Honestly I'm not sure about what can I do since I already use their latest SDK version.
Do you have any suggestion?

**Comment by LetItRock** [comment]
hey @im-perativa! 👋 thanks a lot for your contribution, we do really appreciate that 🤝 

I see that the `@pusher/push-notifications-server` is not maintained well, there is a [PR](https://github.com/pusher/push-notifications-node/pull/65) from May that updates all the libs including the `jsonwebtoken` to a version that has fixed vulnerability issue. Unfortunately, we don't know when it will be merged and released.

My suggestion is to use their REST APIs instead of SDK. I would really appreciate it if you could make this change 🙌 Thank you!

**Comment by im-perativa** [comment]
@LetItRock sure, I have migrated from SDK to API

image

Screenshot 2023-11-02 at 10-27-25 Debug console - Novu - Beams - Pusher

**Review by Cliftonz — APPROVED** [review]

**Pull request merged**
