### PR TITLE
fix(NV-1650): remove the animation in the workflow editor

### LINKED ISSUE #2728: [NV-1650] ✨ Polishing: Remove the animation in the workflow editor
### 📜 Description

Remove the animation in the workflow editor. It is super annoying and you have to wait like a second each time you go to the editor.

### 👟 Reproduction steps

_No response_

### 👍 Expected behavior

No animation

### 📃 Provide any additional context for the Bug.

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

<sub>[NV-1650](https://linear.app/novu/issue/NV-1650/✨-polishing)</sub>

### PR DESCRIPTION
**Pull request by adarshajit**
### What change does this PR introduce?

This PR removes the animation in the workflow editor.

### Why was this change needed?

This was done as a part of the polishing initiative. The changes introduced in this PR fixes #2728 

### Other information (Screenshots)

demo

### CODE REVIEW

**Review by p-fernandez — APPROVED** [review]
Looks ok. Just fix the conflict. Also thanks for sharing a gif of the fix.
CC @LetItRock seems good right?

**Comment by LetItRock** [comment]
> Looks ok. Just fix the conflict. Also thanks for sharing a gif of the fix. CC @LetItRock seems good right?

@adarshajit @p-fernandez 
I'm not sure about this change, in the case of the existing template it blinks, and I do notice it.
That's all because we do reposition the flow editor after it's mounted, and the position we want to have is the top center.
The flow editor doesn't allow doing that with props, unfortunately.

**Comment by p-fernandez** [comment]
@adarshajit might to check what @LetItRock mentions when editing an existing workflow? 🙏🏻

**Comment by LetItRock** [comment]
@adarshajit @p-fernandez 
This is what I meant, it's a small blink when the editor is initialized, it would be nice if we can remove it, but if not let's leave it. My last comment says why it's happening.

https://user-images.githubusercontent.com/2607232/225120086-9eeb70c3-a643-4d0e-b8bd-debf507426b4.mov

**Comment by p-fernandez** [comment]
@scopsy I am not very keen in doing a change that breaks the UX for the Workflow edition. I'd rather keep the current status behaviour rather than patch it. Your call. 🙂

**Comment by scopsy** [comment]
@adarshajit I do aggree that the flicker looks worse than the previously animation :( 

Maybe we can hide the nodes until the first reposition happens to avoid this flicker?

**Comment by LetItRock** [comment]
> @adarshajit I do aggree that the flicker looks worse than the previously animation :(
> 
> Maybe we can hide the nodes until the first reposition happens to avoid this flicker?

the flick is a result because of these steps happen:
- we do always render a trigger node even if the workflow is still fetching
- when the workflow is fetched we do re-render the tree

**Comment by scopsy** [comment]
@LetItRock So seems like we can hide the trigger node until the template is fetched right? I'm totally okey with having it empty until all data is available to perform a proper first render.

**Comment by LetItRock** [comment]
> @LetItRock So seems like we can hide the trigger node until the template is fetched right? I'm totally okey with having it empty until all data is available to perform a proper first render.

@scopsy yes, that's correct

**Comment by scopsy** [comment]
Sounds like a plan, @adarshajit want to give this a try?

**Comment by jainpawan21** [comment]
As we have changed this UI in 0.14.0
I think this issue is now fixed now automatically.

**Comment by scopsy** [comment]
@jainpawan21 good point. Closing this 🙏

**Pull request closed without merging**
