### PR TITLE
docs: include golang code snippets to dashboard

### PR DESCRIPTION
**Pull request by samsoft00**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Docs update, include Golang code snippets to dashboard
- **What is the current behavior?** (You can also link to an open issue here)
No Golang code snippets
- **What is the new behavior (if this is a feature change)?**
Users can copy Golang code snippets
- **Other information**:

### CODE REVIEW

**Comment by scopsy** [comment]
Looks awesome @samsoft00 ! Do you mind adding a photo of the logo on dark and light mode? I think we might need to create a version for each color scheme.

**Comment by EmiliyaGrossman** [comment]
go_dark
go_light

hi @samsoft00 could you please, use those two versions for light and dark 🙏

**Comment by samsoft00** [comment]
Thank you @EmiliyaGrossman @scopsy , I'll work on it asap.

**Comment by samsoft00** [comment]
@EmiliyaGrossman this is PNG, i actually need SVG, can you help with the SVG version? Thank you.

**Comment by samsoft00** [comment]
@scopsy done. Thank you.

**Review by scopsy — APPROVED** [review]
Looks amazing @samsoft00 !

**Pull request merged**
