### PR TITLE
feat: Added SMS.to Chat Provider for Viber

### LINKED ISSUE #4338: [NV-2941] 🚀 Feature: Add SMS.to Chat Provider for Viber
### 🔖 Feature description

Use the [sms.to viber documentation](https://developers.sms.to/#6bdae9bd-b677-420f-b0d2-6e7e430c4bef) to create a new chat provider with the help of the [novu new provider guide](https://docs.novu.co/community/add-a-new-provider#how-to-add-a-new-provider)

### 🎤 Why is this feature needed ?

To add more variety for our community

### ✌️ How do you aim to achieve this?

community contribution

### 🔄️ Additional Information

_No response_

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2941](https://linear.app/novu/issue/NV-2941/🚀-feature-add-smsto-chat-provider-for-viber)</sub>

### PR DESCRIPTION
**Pull request by rvikunwar**
### What change does this PR introduce?

Added New provider "SMSto" for viber to sms providers

### Why was this change needed?

This change Closes #4338 

Light mode
Screenshot 2023-10-09 at 4 59 20 PM

Dark mode
Screenshot 2023-10-09 at 5 00 21 PM

### CODE REVIEW

**Comment by davidsoderberg** [comment]
> > Hi @rvikunwar see the sms provider comments because I guess this will have the same problem?
> 
> which one dark mode icon issue or pipeline failing issue ?

The dark mode issue :)

**Comment by rvikunwar** [comment]
@davidsoderberg can you please check my updated icons for sms.to viber logo for light and dark mode.

**Comment by davidsoderberg** [comment]
Please update branch and provide some screenshots :)

**Comment by scopsy** [comment]
Closing due to inactivity

**Pull request closed without merging**
