### PR TITLE
feat: add showLastUpdateAuthor and showLastUpdateTime in docs

### PR DESCRIPTION
**Pull request by jainpawan21**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
    feat: add showLastUpdateAuthor and showLastUpdateTime in docs
- **What is the current behavior?** (You can also link to an open issue here)
    it is unknown when was last particular doc was updated
- **What is the new behavior (if this is a feature change)?**
   last updated time and author name are shown bottom right on every page.
- **Other information**:
https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#showLastUpdateTime

### CODE REVIEW

**Comment by scopsy** [comment]
@andrewgolovanov could you take a look here? if we need to update here something in terms of design or are we good to merge this? 


CleanShot 2022-08-22 at 14 57 49@2x

**Comment by andrewgolovanov** [comment]
Hi guys!
I would like to get rid of the `italics` in this text - I think it would look much better, what do you think about it?

<details>
<summary>Before:</summary>
Screenshot 2022-08-23 at 13 31 16
Screenshot 2022-08-23 at 13 31 09

</details>

<details>
<summary>After:</summary>
Screenshot 2022-08-23 at 13 27 44
Screenshot 2022-08-23 at 13 30 56

</details>

cc @scopsy

**Comment by jainpawan21** [comment]
@andrewgolovanov, I am looking if there is any config, I can make it regular.

**Review by scopsy — APPROVED** [review]
Thank you @jainpawan21 this looks great!

**Pull request merged**
