### PR TITLE
v0.20.0 LTS node upgrade

### PR DESCRIPTION
**Pull request by scopsy**
### What change does this PR introduce?

Derived from https://github.com/novuhq/novu/pull/4014 by @raikasdev

### CODE REVIEW

**Comment by rifont** [comment]
Node 20 goes LTS next week (24th October), what do we think about fast following with a PR to add Node 20 support?

That way contributor disruption when updating Node versions will be tightly clustered and ideally kept to a minimum, and we won't we'll be on LTS for ~2 years.

**Comment by dammy001** [comment]
> Node 20 enters [Active LTS next week](https://nodejs.dev/en/about/releases/) (24th October), what do we think about fast following with a PR to add Node 20 support?
> 
> 
> 
> That way contributor disruption when updating Node versions will be tightly clustered and ideally kept to a minimum, and we'll be on LTS for ~2.5 years.

@rifont yes, i agree with you. If you check the PR referenced in this, you'll see that I added support for node 20.

**Comment by rifont** [comment]
> @scopsy @rifont how about we drop support for node 10 in public packages? maybe bump to >=14. Currently, it's >=10. I don't think we still have projects on node 10, 12, 14

@dammy001 Great question. We don't yet have a formal stance on support for EOL versions across languages & frameworks for package consumers, so I'd be hesitant to remove support without more data on versions that consumers are using.

What I can say for now is this topic is on the Novu team's radar, and we can seek to drop support after the stance is formalised. We'd be happy to hear your thoughts on the topic to better inform our decision.

**Review by djabarovgeorge — APPROVED** [review]
Tested the change in DEV env, and the flow worked as expected.

**Pull request merged**
