### PR TITLE
feat(web): Add Loading spinner for Update button

### LINKED ISSUE #4703: [NV-3072] Workflow update button should show loading state when clicked
### What?

Whenever we add new step or change anything in any of the workflow step, update button becomes active

### Why? (Context)

After updating the step or workflow settings, when user clicks on the update button. it gets freezes for few seconds. User may click multiple times.

https://github.com/novuhq/novu/assets/39362422/cdc93613-e1c6-4085-b0ce-5f92de5ded6b

### Definition of Done

Update button should show loading state

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-3072](https://linear.app/novu/issue/NV-3072/workflow-update-button-should-show-loading-state-when-clicked)</sub>

### PR DESCRIPTION
**Pull request by iknlaxmi**
### What change does this PR introduce?
Added Loading spinner for Update button.Spinner will appear during updating process.

### Why was this change needed?

Closes #4703 

### Other information (Screenshots)

Screenshot 2023-11-07 at 5 26 18 PM

### CODE REVIEW

**Review by ainouzgali — COMMENTED** [review]
@iknlaxmi we have a loading state in the Button component as part of our design system. You need to add loading={..} to the Button. You can get the loading states from 
`const { isCreating, isUpdating } = useTemplateEditorForm();`

**Comment by iknlaxmi** [comment]
@ainouzgali I will fix it. Thank you.

**Comment by iknlaxmi** [comment]
@ainouzgali updated.

Thank you.

**Review by scopsy — APPROVED** [review]

**Comment by iknlaxmi** [comment]
@scopsy Thank you.

**Pull request merged**
