### PR TITLE
feat: build docker images for arm arch

### LINKED ISSUE #1316: 🚀 Feature: Arm64 Support
### 🔖 Feature description

Arm64/aarch64 support for docker images.

### 🎤 Why is this feature needed ?

Cloud is moving to Arm64 compute (probably cost related), many projects are already preparing for this new arch. 
An example of this is the Oracle Cloud Offer in Amphere A1 VM’s.

### ✌️ How do you aim to achieve this?

I’ve already downloaded the repo thinking about making a PR with all the changes, but as for now I see some problems (as for now only one, but if I see more with add it with an edit):

1.  API, web, widget and embed depends in nikolaik/python-nodejs with as for now is only amd64. There’s already [nikolaik/python-nodejs#38](https://github.com/nikolaik/docker-python-nodejs/issues/38) but with no timeline or notice.

### 🔄️ Additional Information

_No response_

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by DaleWebb**
### What change does this PR introduce?

Builds the docker images for arm64 and amd64 architectures using buildkit emulation

### Why was this change needed?

Closes #1316

### Other information (Screenshots)

- Had to remove the base image: `nikolaik/python-nodejs:python3.10-nodejs16-alpine` as this couldn't be compiled for arm.
- Build times might increase significantly...

### CODE REVIEW

**Comment by scopsy** [comment]
@Cliftonz should we utilize depot in someway for this? Also, how this should affect the way we push to GHCR? Or no further action is needed from our side there

**Comment by underfisk** [comment]
@scopsy Any thoughts on this one? I've been loving the integration of Novu but for m1 mac's its being a blocker as sometimes the API crashes and needs manual reloading

**Comment by scopsy** [comment]
Would love to have @Cliftonz take a look at this to make sure we are not making the docker files larger and it's backwards compatible 🙏

**Comment by Cliftonz** [comment]
Taking a look at this now

**Comment by Cliftonz** [comment]
@DaleWebb Sorry this took so long, I need to look a little deeper at some of our internal tooling to see if this can be accomplished with the process we already have. 

@scopsy Should be able to give me access sunday and I will take a look at this monday.

**Comment by Cliftonz** [comment]
@DaleWebb @scopsy  Following up on this Depot is not currently building ARM containers otherwise it will block all of our builds. I have reached out to support to get this solved hopefully as soon as possible.

Otherwise, the local docker build does not seem like any issue other then needing to run ```docker buildx create --use``` before it would actually build multiple architectures.

**Comment by Cliftonz** [comment]
The issue was with depot waiting for context to be passed in on std in and not timing out. 
This is getting with with depot right now.

**Comment by jainpawan21** [comment]
@Cliftonz Can we close/merge this PR?

**Comment by Cliftonz** [comment]
> @Cliftonz Can we close/merge this PR?

@jainpawan21 Not yet, I will look over this monday

**Comment by Cliftonz** [comment]
@DaleWebb @underfisk I am going to have to delay working on this for the moment. 
I have resiliency issues I need to attend to at this time.
My apologies

**Comment by underfisk** [comment]
> 

Ah no worries, lately I've developed a tool with Playwright that automates the setup which was a thing that wasn't possible with Novu because the SDK always demands an API key, there are no "root/master" credentials which I hope there were.
My workaround now is a health check that does `wget http:/.../v1/health-check` to the `novu-api` because that often gets the following error:
```bash
assertion failed [result.value != EEXIST]: VmTracker attempted to allocate existing mapping
```

Let me know once there are some news regarding ARM support as it's starting to become somewhat important for our codebase

**Comment by Cliftonz** [comment]
Thanks for letting us know. I will see what I can do shortly.

**Comment by paulwer** [comment]
are there any updates regarding arm64 support? ❤️

**Comment by Cliftonz** [comment]
Not at this current time, I really hate to do this but we have much higher priorities from the business and reliability side of things. This is definitely a great to have though we do not have the time currently to implement this in our pipeline.

**Comment by AliaksandrRyzhou** [comment]
Closed by [PR 5139](https://github.com/novuhq/novu/pull/5139)

**Pull request closed without merging**
