### PR TITLE
Added matrix

### LINKED ISSUE #128: [NV-178] - Add new provider Matrix (matrix.org)
No support for Matrix notifications

Solution I'd like:
Support for it.

Additional Context:
matrix.org

### PR DESCRIPTION
**Pull request by 07tAnYa**
### What change does this PR introduce?

This PR adds matrix as one of the providers.

FIXES #128

### CODE REVIEW

**Review by 07tAnYa — COMMENTED** [review]
will consider this,

**Comment by 07tAnYa** [comment]
Sir, could you please clearify the areas where the specific changes need to be made.

**Review by 07tAnYa — COMMENTED** [review]
once again  I am getting a lot of issues in getting the matrix provider. Sir kindly assist me with this. For the above said review I will change the code to JS . But for now, please tell how can I achieve this . Sir as I am a complete beginner in this , you can teach me from the very basic. I promise that as a fresher I will learn all these very quickly. and will not make you feel regret.

**Comment by Cliftonz** [comment]
@07tAnYa You can follow things guide on how to create a provider.
https://docs.novu.co/community/add-a-new-provider#how-to-add-a-new-provider

Please create a new PR if you are still assigned to the issue and in javascript.

Thank you for working with Novu!

**Comment by 07tAnYa** [comment]
Ok sure , and thank you

**Pull request closed without merging**
