### PR TITLE
fix: [NV-2841] Fixed issue of channel icons in light theme due to duplicate id in SVG

### LINKED ISSUE #4260: [NV-2841] Workflow Editor - channels icons are white in light theme
## Reproduction steps
Light theme - channels icon over provider image are always white.
image

Also on hover on the sidebar:
image

Dark theme for reference: 
image

## Definition of done
- RIGHT TOOLBAR. When a user hover over the icons for Email and SMS in light theme it should behaves same way as other channels
- NODE. The channel icons (small icon on the right bottom corner near the provider icon) on the step node should be the following:
  - Dark theme: #BEBECC (B80)
  - Light theme: #828299 (B60)

### PR DESCRIPTION
**Pull request by Gaurav0493**
### What change does this PR introduce?
This PR fixes the issue with channel icon color in light theme in the workflows.

This issue was due to duplicate id of linearGradient in SVGs of channel images.
When a channel is added in the workflow the duplicate id of the linearGradient gets added in the DOM due to which the color of the image defaults to white and i.e. the image is not visible in the white theme. 

To fix this issue, I have used timestamp as a unique Id for these linearGradient. This will allow having multiple channel icons in the DOM. 

### Why was this change needed?
The changes fix the issue with channel icons in the light theme. 

For example: When I add an email channel into the workflow ( in light theme) and then hover on the email channel from the actions menu to add the email channel again into the workflow the email channel disappears. 

With this PR the above issue is fixed. 

Closes #4260

### Fix Screenshots
Light Mode
Screenshot 2023-10-03 at 6 02 48 PM
Screenshot 2023-10-03 at 6 03 07 PM

Dark Mode
Screenshot 2023-10-03 at 6 54 13 PM

===============================================================
### This PR also fixes the issue with the color of filter icon on the Configure page for the channel in light theme. 
Before fix
Screenshot 2023-10-03 at 6 04 39 PM
After fix
Screenshot 2023-10-03 at 6 05 02 PM

### CODE REVIEW

**Comment by scopsy** [comment]
@Gaurav0493 there are some merge conflicts, could you please take a look at those?

**Comment by LetItRock** [comment]
hey @Gaurav0493 👋 could you please give me the rights to push the changes to your fork? we would love to merge this PR 🙏

**Comment by Gaurav0493** [comment]
> hey @Gaurav0493 👋 could you please give me the rights to push the changes to your fork? we would love to merge this PR 🙏

Hey @LetItRock I have sent invite to you for my fork.

**Comment by LetItRock** [comment]
> > hey @Gaurav0493 👋 could you please give me the rights to push the changes to your fork? we would love to merge this PR 🙏
> 
> Hey @LetItRock I have sent invite to you for my fork.

thank you! 🙌

**Pull request merged**
