### PR TITLE
Fix nested handlebar variables

### LINKED ISSUE #2040: [NV-1191] 🐛 Bug Report: Nested handlebar variables aren't shown in Template variable protection and defaults
### 📜 Description

When there are nested variables inside `each`/`if` handlebar statements they aren't shown under the template to allow the user to pick defaults and "is required".

### 👟 Reproduction steps

Create template with a variable inside a block statement. For example

```
{{#each step.events}}
    {{title}}
{{/each}}
```

### 👍 Expected behavior

It should show all nested variables

### 👎 Actual Behavior with Screenshots

Only shows top variables

### 💻 Operating system

MacOS

### 🤖 Node Version

v16.13.1

### 📃 Provide any additional context for the Bug.

*No response*

### 👀 Have you spent some time to check if this bug has been raised before?

* [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

* [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

> From [SyncLinear.com](https://synclinear.com)

### PR DESCRIPTION
**Pull request by guywal**
### What change does this PR introduce? 

Fixes the usage of `@handlebars/parser` in [VariableManager](https://github.com/novuhq/novu/blob/next/apps/web/src/components/templates/VariableManager.tsx). 
Nested variables inside `BlockStatement` should be taken from `.program.body`.

### Why was this change needed?

There was a bug where nested variables weren't shown in the Variables manager.

fixes #2040 

### Other information (Screenshots)

image

### CODE REVIEW

**Review by p-fernandez — COMMENTED** [review]
Thanks for this contribution. Is very useful.
Just a question. Does this support multiple nesting levels variables in a recursively way? If so could you add a test for that?
@davidsoderberg does this PR conflicts with your current work of the preview and templates?

**Comment by davidsoderberg** [comment]
> Thanks for this contribution. Is very useful. Just a question. Does this support multiple nesting levels variables in a recursively way? If so could you add a test for that? @davidsoderberg does this PR conflicts with your current work of the preview and templates?

No but maybe with @ainouzgali ?

**Comment by guy-wal** [comment]
> Thanks for this contribution. Is very useful.
> 
> Just a question. Does this support multiple nesting levels variables in a recursively way? If so could you add a test for that?
> 
> @davidsoderberg does this PR conflicts with your current work of the preview and templates?

Happy to contribute!
It does support deeply nested, there is a test for it. Unless you think there is something I missed

**Comment by p-fernandez** [comment]
> > Thanks for this contribution. Is very useful.
> > Just a question. Does this support multiple nesting levels variables in a recursively way? If so could you add a test for that?
> > @davidsoderberg does this PR conflicts with your current work of the preview and templates?
> 
> Happy to contribute! It does support deeply nested, there is a test for it. Unless you think there is something I missed

Sorry, you are right. I misread the deeply nested thinking they were all in the same level, like an array.

**Review by scopsy — APPROVED** [review]
Looks great @guywal, love the added tests!

**Pull request merged**
