### PR TITLE
Refactored a punctuation in Readme.md

### PR DESCRIPTION
**Pull request by Srikarmk**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Changed a punctuation in the why section.

- **Why was this change needed?** (You can also link to an open issue here)
To improve readability and to provide clarity

- **Other information**:

### CODE REVIEW

**Comment by scopsy** [comment]
@Srikarmk Do you mind sharing why this change was needed? I'm not sure why one is more cohesive than the other than a personal style. Would appreciate an explanation, perhaps I'm missing something.

**Comment by Srikarmk** [comment]
@scopsy well usually a semicolon doesn't explain the statement after it but a hyphen points to the explanation , hence I felt that this might be a better option as a punctuation mark in the sentence. Thank you for the check , in the end it's your decision.

**Comment by scopsy** [comment]
@Srikarmk couldn't find any specific case for a hyphen use here: http://www.butte.edu/departments/cas/tipsheets/punctuation/hyphen.html

Do you think we can just convert it to a `,` ?

**Comment by Srikarmk** [comment]
Sure that works too , i'll make a PR then . Thank you @scopsy

**Pull request closed without merging**
