### PR TITLE
fix(web): fixed every selected image upload on aws bug

### PR DESCRIPTION
**Pull request by devblin**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Fixes issue of every chosen image upload on aws-s3.

- **Why was this change needed?** (You can also link to an open issue here)
#829

### CODE REVIEW

**Comment by devblin** [comment]
@scopsy please review

**Comment by davidsoderberg** [comment]
@devblin would be great if we could do some test to prevent this bug in the future 😄

**Comment by devblin** [comment]
@davidsoderberg I have tested this fix locally and it looks good.

**Comment by davidsoderberg** [comment]
@devblin could some automatic tests be done for this?

**Comment by devblin** [comment]
@davidsoderberg , You mean adding tests in `apps/web/cypress/tests` right ?

**Comment by davidsoderberg** [comment]
Yes if there is a way to interact with it in the frontend it would be great :)

**Review by scopsy — APPROVED** [review]

**Comment by scopsy** [comment]
@devblin seems like this is breaking the current tests :( Will you have time to take a look at this?

**Comment by scopsy** [comment]
Closing this for now due to inactivity, we can re open once the tests are passing 🙏

**Pull request closed without merging**
