### PR TITLE
feat: add ff for information architecture

### PR DESCRIPTION
**Pull request by BiswaViraj**
### What change does this PR introduce?
- Added Feature flag for Information Architecture
- Added FF on the Launchdarkly Dashboard.

### CODE REVIEW

**Review by antonjoel82 — APPROVED** [review]
Nice! Do we need to put the flag in `libs/shared/src/types/feature-flags/feature-flags.ts`?

**Comment by BiswaViraj** [comment]
@antonjoel82 Yes, as we import this enum on both web and API. It acts like a central place for FF config

**Comment by antonjoel82** [comment]
> @antonjoel82 Yes, as we import this enum on both web and API. It acts like a central place for FF config

Are you planning to add that to this PR then?

**Comment by BiswaViraj** [comment]
@antonjoel82 Sorry, am confused,
I have already added the flag in the `libs/shared/src/types/feature-flags/feature-flags.ts` file https://github.com/novuhq/novu/blob/170ab77ccd790b79d783da43cb5300ddc63e566c/libs/shared/src/types/feature-flags/feature-flags.ts#L11

Do you mean to add it to some other file?

**Comment by antonjoel82** [comment]
> @antonjoel82 Sorry, am confused, I have already added the flag in the `libs/shared/src/types/feature-flags/feature-flags.ts` file
> 
> https://github.com/novuhq/novu/blob/170ab77ccd790b79d783da43cb5300ddc63e566c/libs/shared/src/types/feature-flags/feature-flags.ts#L11
> 
> Do you mean to add it to some other file?

Ah sorry! I definitely misread this as being added in `shared-web`. Should be good to go

**Pull request merged**
