### PR TITLE
Created CODE_OF_CONDUCT for the Novu main repository

### PR DESCRIPTION
**Pull request by Rutam21**
### What kind of change does this PR introduce?
This PR adds the Github Code_Of_Conduct 2.0 for the Contributors to the repository.

### Is there an open issue for this?
This issue fixes https://github.com/novuhq/novu/issues/1037

### CODE REVIEW

**Comment by Rutam21** [comment]
@scopsy Please review. Thanks.

**Comment by scopsy** [comment]
Thank you, @Rutam21 could you just rename the file to have the .md ending for easier access and readability?

**Comment by Rutam21** [comment]
@scopsy I have updated the file name.

**Review by scopsy — APPROVED** [review]
Perfect!

**Pull request merged**
