### PR TITLE
Adding support for vue-2

### LINKED ISSUE #2421: [NV-1423] 🚀 Feature: Vue 2 support in the vue-notification-center package
### 🔖 Feature description

Add support for the Vue 2 in the `vue-notification-center` package.

This was requested on the Discord and could be a quick win for us: https://discord.com/channels/895029566685462578/937309213036785744/1059265218368245860

Suggestion from @florian-lefebvre:
It should be easy to implement with this library: https://github.com/vueuse/vue-demi

The person who will be working on this should verify if it works with both Vue 2 and Vue 3, we do have an example Vue 3 app in the repo, please make sure that it still works there.

### 🎤 Why is this feature needed ?

It will allow the companies that develop their apps with Vue 2 to use the Notification Center much more effortlessly. 

### ✌️ How do you aim to achieve this?

Using this lib: https://github.com/vueuse/vue-demi

### 🔄️ Additional Information

_No response_

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1423](https://linear.app/novu/issue/NV-1423/🚀-feature-vue-2-support-in-the-vue-notification-center-package)</sub>

### PR DESCRIPTION
**Pull request by Cxxshyy**
### What change does this PR introduce?

Currently we only have support for Vue-3 so this change aims to add support for companies wishing to use vue-2 in their projects

### Why was this change needed?

Closes #2421

### CODE REVIEW

**Comment by florian-lefebvre** [comment]
Is there any way we can test such PR @LetItRock ?

**Comment by Cxxshyy** [comment]
> Is there any way we can test such PR @LetItRock ?

i'll also be pushing a commit for  the vue 2 example soon

**Comment by LetItRock** [comment]
@Cxxshyy @florian-lefebvre 
Ideally, we should run the same set of e2e tests that we do run for the `widget` app, but right now, we don't have Cypress configured. I did the tests manually before.

**Comment by Cxxshyy** [comment]
@LetItRock how do i run the e2e test manually

**Comment by Cxxshyy** [comment]
i also dont know where to get values for ```VITE_NOVU_APP_IDENTIFIER=YOUR_APP_IDENTIFIER
VITE_NOVU_SUBSCRIBER_ID=YOUR_SUBSCRIBER_ID```

**Comment by Cxxshyy** [comment]
I've also introduced the new file structure suggested in the issue discussion 
```examples/vue2-notification-center-example
examples/vue3-notification-center-example```

**Comment by LetItRock** [comment]
@Cxxshyy 
> how do i run the e2e test manually

We don't have e2e tests for the `vue-notification-center`. What I did before was I just manually verified on the example app if the notification center component works fine.

> i also dont know where to get values for VITE_NOVU_APP_IDENTIFIER=YOUR_APP_IDENTIFIER VITE_NOVU_SUBSCRIBER_ID=YOUR_SUBSCRIBER_ID

`VITE_NOVU_APP_IDENTIFIER` is `Application Identifier` which can be found in the Web app on the Settings page under the `API Keys` tab.
Screenshot 2023-01-08 at 22 09 17

`VITE_NOVU_SUBSCRIBER_ID` is your subscriber ID which you put on when you do call the `trigger` action.

---

By default the Notification Center component connects to the production, but if you need you can change it to local API/WS app instances, just pass the `backendUrl` and `socketUrl`

**Comment by Cxxshyy** [comment]
sorry im gonna need more info so i created an account and got the sub id

**Comment by Cxxshyy** [comment]
like where do i insert the trigger function

**Comment by Cxxshyy** [comment]
if possible could i get a more in depth guide @LetItRock

**Comment by LetItRock** [comment]
@Cxxshyy 
to test the notification center you need to:

In the Web app
- create a new Notification Template with an `In-App` step in the workflow and fill it with some data
- save it
- click on `Test Workflow`, then copy the `subscriberId` 
- go to Settings -> API Keys -> copy `Application Identifier` (applicationIdentifier)

In the Vue example app
- pass the `NotificationCenterComponent` props: `backendUrl, socketUrl` depending on where you want to connect (by default it's configured to talk with prod, so if you copied other prod values then you don't need to setup these); `applicationIdentifier`, and `subscriberId`
- run the app locally

Go to the Web app:
- find the created Notification Template
- click on `Test Workflow`
- click `Trigger`

Now if everything was set up properly you should receive the notification in the Vue example app.
Hope it clarifies everything.

Screenshots:
Screenshot 2023-01-09 at 19 06 12

Screenshot 2023-01-09 at 19 06 21

Screenshot 2023-01-09 at 18 47 36

Screenshot 2023-01-09 at 18 47 44

**Comment by Cxxshyy** [comment]
@LetItRock excellent guide i managed to do it with current working release so will now implement it with the pr

**Comment by Cxxshyy** [comment]
i also closed this pr as io had to delete my fork and restart

**Pull request closed without merging**
