### PR TITLE
feat: add maithili language support

### LINKED ISSUE #1509: 🚀 Feature: i18n - Maithili Support
### 🔖 Feature description

Adding Maithili language support.

### 🎤 Why is this feature needed ?

For Maithili people who are not familiar with English.

### ✌️ How do you aim to achieve this?

- Add a new translation file here: packages/notification-center/src/i18n/languages. You can follow the en.ts example.
- Add your translation import to the TRANSLATIONS object at packages/notification-center/src/i18n/lang.ts
- Add the language code to I18NLanguage type at lang.ts file.
- Updating /docs/docs/notification-center/react-components.md for the language added.
- Submit a PR

### 🔄️ Additional Information

_No response_

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by thenishantsapkota**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- This PR introduces support for the Maithili language for the @novu/notification-center component interface.

- **Why was this change needed?** (You can also link to an open issue here)
- For internationalization

- Resolves #1509

### CODE REVIEW

**Comment by thenishantsapkota** [comment]
@p-fernandez Please review the changes

**Comment by davidsoderberg** [comment]
Hi @thenishantsapkota I see that you have already submitted support for another lang here: https://github.com/novuhq/novu/pull/1505
Do you know both of them?

**Comment by thenishantsapkota** [comment]
> Hi @thenishantsapkota I see that you have already submitted support for another lang here: #1505 Do you know both of them?

Maithili is quite widely spoken in my area.
That's why I am translating this.

**Comment by p-fernandez** [comment]
There is not language code for Maithili in [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) and it is the specification we are using so far (2 character language code).
I am not sure if we should allow this PR to be merged until we check if Novu can support ISO 639-2 or ISO 639-3 language codes (3 characters language code).
@scopsy @davidsoderberg

**Comment by p-fernandez** [comment]
We have the same situation with other languages without code in ISO 639-1.
https://github.com/novuhq/novu/pull/1580

**Comment by scopsy** [comment]
Unfortunately we won't be able to support language in other than ISO 639-1 specification right now. We might reconsider this but must treat it separately in a different issue. For the Maithili language, novu users could still use it by providing a custom i18n object for the component.

**Pull request closed without merging**
