### PR TITLE
fix: first-child replaced with first-of-type due to SSR warning

### LINKED ISSUE #4293: [NV-2932] Fix the pseudo class ":first-child" warning shown in the console
## Reproduction Steps
1. Navigate to the Workflows page
2. Open any workflow
3. The warning is shown: `The pseudo class ":first-child" is potentially unsafe when doing server-side rendering. Try changing it to ":first-of-type". is printed in the console.`

image

## Expected Behaviour
- fix the issue and there should be no warnings printed

### PR DESCRIPTION
**Pull request by UzairNoman**
### What change does this PR introduce?

This PR replaces all the instances of first-child with first-of-type to solve the warning issue of SSR. The first-of-type is safe to replace in all the cases and weren't even taking an effect previously as <stop> tags are always used inside LinearGradient or RadialGradient tags.
See: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/stop

### Why was this change needed?

The warning is shown: `The pseudo-class ":first-child" is potentially unsafe when doing server-side rendering. Try changing it to ":first-of-type". is printed in the console.`

Fixes #4293

### Other information (Screenshots)

image

### CODE REVIEW

**Comment by LetItRock** [comment]
hey @UzairNoman! 👋 thanks for the contribution 🤝
We do value your time and effort, but we would like to give everyone a fair chance to contribute to our repository.
If the person who was assigned to the original ticket submits the PR we will prefer that one, instead of yours. But if the person won't be able to submit the PR or will be unresponsive we will revisit your PR.
For now, I'm closing it.

**Comment by UzairNoman** [comment]
Hi @LetItRock, can you please review this one :)

**Review by mesloubi2021 — COMMENTED** [review]
طلب سحب

**Review by LetItRock — APPROVED** [review]
thanks a lot! 🙌 🚀

**Comment by UzairNoman** [comment]
@LetItRock, is there anything pending from my side? how and when will it be merged?

**Comment by LetItRock** [comment]
> @LetItRock, is there anything pending from my side? how and when will it be merged?

nope, thanks everything is fine 🙂 we will merge it soon, don't worry about that 🙌

**Pull request merged**
