### PR TITLE
feat(nv-2233): Add support for FCM optional data payload

### LINKED ISSUE #2233: 🚀/🐛 Feature/Bug: No possibility of sending FCM data payload
### 🔖 Feature description

Dear all

With the commit `8c30377ddd806d4c06d51ba4f9ee6541ab593e38` there was the introduction of the new FCM API, where novu uses now `sendMulticast`.

I'd like to send some payload data to handle clicks on push notifications, i.e. I want to use the `data` property for a received push notification. 

In `fcm.provider.ts`, there's this:

```typescript
  async sendMessage(
    options: IPushOptions
  ): Promise<ISendMessageSuccessResponse> {
    delete (options.overrides as any)?.deviceTokens;
    const res = await this.messaging.sendMulticast({
      tokens: options.target,
      notification: {
        title: options.title,
        body: options.content,
        ...options.overrides,
      },
    });
```

So, Novu only uses the `notification` property of the `MulticastMessage`, which is an extension of the a [BaseMessage](https://firebase.google.com/docs/reference/admin/node/firebase-admin.messaging.basemessage.md#basemessage_interface). The `BaseMessage` also allows for a `data` property, which then can be accessed when the notification is received. 

Be aware, that just using `payload` as the `data` property might be an issue, since payload can be of any type, e.g. `payload : { someList : [] }` would fail, because the `data` property must be `{ [key: string]: string; }` according to the docs.

Now, I would do and push this feature myself but sadly I'm not experienced enough with JS to build the application... 

Thanks!

### 🎤 Why is this feature needed ?

To act according to the received data when clicking on a received FCM push notification, e.g. show a different screen than usual etc.

### ✌️ How do you aim to achieve this?

See above.

### 🔄️ Additional Information

_No response_

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

### PR DESCRIPTION
**Pull request by ttlgeek**
### What change does this PR introduce? 

Adds support for FCM optional data payload.

[FCM docs link](https://firebase.google.com/docs/cloud-messaging/concept-options#notification-messages-with-optional-data-payload)
### Why was this change needed?

Closes #2233

### CODE REVIEW

**Comment by ttlgeek** [comment]
@LetItRock @scopsy @jainpawan21

**Review by viktorlarsson — COMMENTED** [review]
Nice!

**Comment by LetItRock** [comment]
hey @ttlgeek 👋 
Thanks for your contribution. We do already have [a similar PR](https://github.com/novuhq/novu/pull/2135) to this one but that one does it a little differently, plus it handles the data/notification messages in FCM. Probably we will stick to that one because of the additional functionality.

@scopsy any thoughts?

**Comment by ttlgeek** [comment]
@LetItRock The PR you mentioned seems to me has been abandoned by its author.

If this truly the case, I'd be more than happy to take your suggestions/additional functionality requirements and discuss how we can make this PR the best it can be to support the FCM data feature.

If you guys decide to go with my PR, please let me know and I'd be more than happy to work on this feature.

Thanks :)

**Comment by LetItRock** [comment]
thank you for your intention and commitment @ttlgeek! 
I've contacted @raikasdev and he said that he will polish his PR soon.

**Comment by ttlgeek** [comment]
Okay, i'll go ahead and close this MR then.

**Comment by KristofDeTroch** [comment]
Could we get an update on this feature?

**Comment by raikasdev** [comment]
> Could we get an update on this feature?

Implemented in #2007 
View FCM page on the documentation for usage.

**Pull request closed without merging**
