### PR TITLE
added greetings workflow

### LINKED ISSUE #1391: Greetings
- **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] question about the decisions made in the repository
  -  [ ] question about how to use this project

- **Summary**

_I will add a github action which greets user whenever someone makes a PR or Issue by posting a comment._

- **Other information**

Can I do that @nevo-david ?

### PR DESCRIPTION
**Pull request by MrKrishnaAgarwal**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Feature: I have added a workflow that greets user whenever they open PR or Issue

- **Why this change was needed?** (You can also link to an open issue here)

Closes #1391 

- **Other information**:

_greets user whenever someone makes a PR or Issue by posting a comment._

### CODE REVIEW

**Comment by MrKrishnaAgarwal** [comment]
cc @scopsy

**Comment by MrKrishnaAgarwal** [comment]
### Demo:

image


**See Here:** https://github.com/MrKrishnaAgarwal/novu/issues/2

**Comment by MrKrishnaAgarwal** [comment]
**This action will check if it's the first pull request or issue to the repo and greet them.**

**Comment by MrKrishnaAgarwal** [comment]
It's a great workflow to interact with people 😄 and to engage with them 😇

**Comment by scopsy** [comment]
@MrKrishnaAgarwal Unfortunately I don't see the value for this at that point in our repository as I believe it will mostly create a lot of noise for issues and PR's. 

Will be closing this for now as a won't fix, maybe we can reconsider this later down the road.

**Pull request closed without merging**
