### PR TITLE
feat: Add D7Networks SMS Provider

### LINKED ISSUE #4366: [NV-2950] 🚀 Feature: Add D7Networks SMS Provider
### 🔖 Feature description

Use the [d7 sms docs](https://d7networks.com/docs/SMS/Send-SMS/) to create a sms provider while following the [Novu's guide to building a provider](https://docs.novu.co/community/add-a-new-provider#how-to-add-a-new-provider)

### 🎤 Why is this feature needed ?

To give the community more providers

### ✌️ How do you aim to achieve this?

community contributions

### 🔄️ Additional Information

_No response_

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2950](https://linear.app/novu/issue/NV-2950/🚀-feature-add-d7networks-sms-provider)</sub>

### PR DESCRIPTION
**Pull request by skoriop**
### What change does this PR introduce?

Adds the D7Networks SMS Provider

### Why was this change needed?

Closes #4366 

### Screenshots

01 Create-app

image

image

image

image

### CODE REVIEW

**Comment by davidsoderberg** [comment]
Hi @skoriop could you please provide some screenshots of how it looks?

**Comment by skoriop** [comment]
Sure, I've updated my PR message with a few.

**Comment by davidsoderberg** [comment]
Also could you check if it works with the new multi provider config to enable it change the fallback to true in /apps/web/src/hooks/useFeatureFlags.ts on line 34.

**Comment by skoriop** [comment]
Yup

**Comment by scopsy** [comment]
@skoriop my apologies for the late reply, but could you help with merging conflicts so we can push this forward?

**Comment by skoriop** [comment]
@scopsy conflicts should be resolved now

**Comment by scopsy** [comment]
Closing due to inactivity

**Pull request closed without merging**
