### PR TITLE
feat: #686 add termii sms provider

### PR DESCRIPTION
**Pull request by samsoft00**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
New [Termii](https://developers.termii.com/messaging) SMS Provider.

- **What is the current behavior?** (You can also link to an open issue here)
Use Termii as a provider.

- **What is the new behavior (if this is a feature change)?**

- **Other Information**:

### CODE REVIEW

**Comment by samsoft00** [comment]
Please @davidsoderberg @scopsy please let me know the next step.

**Comment by scopsy** [comment]
@samsoft00 so now looks like this part is great! Could you just run pnpm install from root to update the `pnpm.lock` file and commit it? This should fix the CI for Test Providers.

Regarding the implementation of the platform and API, we will need to create a handler in the API (I think @davidsoderberg pointed you to its location). And then we only have left to add it in the UI of @novu/web project. Unfortunately, creating a provider guide is missing this part since our migration to the API service.

@djabarovgeorge will create a guide for this soon and will update you on this (we can even upgrade our current hygen config to scaffold most of the changes)

**Comment by samsoft00** [comment]
Thank you @scopsy, I've updated `pnpm.lock` and pushed the changes.

Yes, I have the guide, I will work on it once this is approved + UI.

**Review by scopsy — APPROVED** [review]
Looks amazing @samsoft00 ! Merging this to main, and we can handle the handlers and UI in a different PR. 🙏

**Pull request merged**
