### PR TITLE
Fix/update contributing.md

### LINKED ISSUE #4597: 📚 Docs Feedback: Instructions not clear after spinning docker-compose.yml for development
### Duplicates

- [X] I have searched the existing issues

### Related page

https://github.com/novuhq/novu/tree/next/docker/local/development

### Kind of issue

Missing information

### Issue description

I was trying to create development environment to work on web but there was no clear instructions on contribution.md how to spin the docker container and work on the different repos. There is only single link [https://docs.novu.co/community/run-in-local-machine](url) how to setup novu locally. 

After trying I found the docker-compose.yml file in root->docker->local->development->docker-compose.yml. The docker-compose is running but after that there is not clear instructions how to access web, api, workers and other repos for contributions. In terminal it is clear that localstack, mongodb and redis is running.  But I am not sure how to access web repo for development. 
py1

There is no clear instructions how to use development compose file for development and to do after that.
py2

### Context 🔦

I am interested in contributing frontend development and api development/testing but I don't want to install everything on my local machine. I was looking for decker image to run the code but there is no relevant  document nor topics to go through.

### PR DESCRIPTION
**Pull request by Priyanshuthapliyal2005**
### What change does this PR introduce?

This pull request introduces additional instructions in the CONTRIBUTING.md file, specifically focusing on clarifying the steps to access the web, API, and worker repositories after successfully running the docker-compose.yml file. These changes aim to improve the onboarding experience for contributors interested in frontend and API development/testing.

### Why was this change needed?

Closes #4597 

To fix issue the faced by contributuors on navigating the development environment setup. 
By enhancing the instructions in CONTRIBUTING.md, we aim to provide a more straightforward and accessible process for contributors, ultimately streamlining the web development setup in Novu.

### Other information (Screenshots)
image

### CODE REVIEW

**Comment by djabarovgeorge** [comment]
Hey @Priyanshuthapliyal2005 thanks for taking the time to improve the CONTRIBUTING.md file, however, I am still not convinced that we need to duplicate the docs data here.
The contributing md file should have general instructions and if the user needs something specific info he could look for it in the docs.
But I could be mistaken so would love to hear others opinions on the matter @jainpawan21 do you think those additional data is needed here?

**Comment by Priyanshuthapliyal2005** [comment]
@djabarovgeorge , thank you for your thoughtful feedback. I understand the concern about keeping the CONTRIBUTING.md file concise. However, it's essential to address the fact that some contributors face difficulties finding the required information in the documentation due to outdated links.

To tackle this challenge effectively, I propose a solution: assigning me to the documentation section. By being assigned to documentation updates, I can ensure that the links in the CONTRIBUTING.md file stay current without duplicating the entire documentation. This approach not only maintains the file's conciseness but also ensures that contributors have accurate and accessible information.

Assigning me to the documentation section would enable prompt updates, resulting in a more seamless experience for contributors navigating the onboarding process. I look forward to your thoughts on this suggestion and appreciate your consideration.

@jainpawan21 , your insights into this matter would be highly valuable.

**Comment by jainpawan21** [comment]
Hi @Priyanshuthapliyal2005 

As George suggested, it will be difficult to maintain same information at two places.
This information is in our docs

**Comment by jainpawan21** [comment]
Closing this PR for now.

Thanks for your contributions

**Pull request closed without merging**
