### PR TITLE
Added words for Kannada language translation and also changed the language code

### PR DESCRIPTION
**Pull request by Atharva1723**
What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)
It adds two more words for the translation to kannada and changes the actual language code for Kannada

Why was this change needed?
Because settings and no new notification words were not translated into Kannada
And the actual code for kannada language is kn not ka

### CODE REVIEW

**Comment by Atharva1723** [comment]
Please review this PR ? @djabarovgeorge @davidsoderberg @scopsy

**Review by p-fernandez — APPROVED** [review]
Thank you for your contribution. 🌟

**Comment by Atharva1723** [comment]
@p-fernandez thank you for approving the PR . Do you know why is the Web Cypress check failing ?

**Comment by p-fernandez** [comment]
> @p-fernandez thank you for approving the PR . Do you know why is the Web Cypress check failing ?

Flakey internal tests. I am checking anyway. Your changes shouldn't affect.

**Comment by Atharva1723** [comment]
> > @p-fernandez thank you for approving the PR . Do you know why is the Web Cypress check failing ?
> 
> Flakey internal tests. I am checking anyway. Your changes shouldn't affect.

Okay, If any changes are required tell me accordingly

**Comment by Atharva1723** [comment]
Still it is failing

**Comment by p-fernandez** [comment]
Merging with the failing test as it is unrelated to the PR and seems to be related to Cypress and Webpack versions.
https://github.com/cypress-io/cypress/discussions/22682

**Comment by Atharva1723** [comment]
Can I create a typescript file for Georgian as that is not created before

**Pull request merged**
