### PR TITLE
feat(brevo): add support for brevo email templates

### LINKED ISSUE #5122: 🚀 Feature: Brevo Email Templates
### 🔖 Feature description

Add support for Brevo email templates (and template variables)

### 🎤 Why is this feature needed ?

Currently, Novu does not support email templates for Brevo.
The Brevo template engine allows, for example, to create fairly advanced conditions based on one or more variables (display conditions, loops, etc.).

I personally use Brevo in my company, and being able to connect our email templates with Novu would be much more convenient and powerful.

### ✌️ How do you aim to achieve this?

Adding templates is rather simple, Brevo requires the addition of two parameters (templateId, and params) to the request body.

templateId is an int, and params is an object.

The customData property, in 'overrides.email', could be used. The SendGrid provider already implements this function in the same way.

### 🔄️ Additional Information

_No response_

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by ludorenzetti**
Hi guys !

First of all, a big thank you for this great work on Novu! ❤️ 

While working with Novu, I realized that email templates for Brevo (formerly SendinBlue) were not supported. This is why I am opening this little PR.

Hoping it will be available in the next release! 🤞 

Don't hesitate if there is a need for more info or modification.

Closes #5122

### CODE REVIEW

**Comment by scopsy** [comment]
@ludorenzetti thank you so much for your contribution! Do you mind also introducing a small section with this information here: https://docs.novu.co/channels-and-providers/email/sendinblue 

Repo: https://github.com/novuhq/docs/

**Review by scopsy — APPROVED** [review]

**Comment by madebyfabian** [comment]
That's awesome! I just discovered the exact same need. If this PR is merged, would it also work with digests? Meaning that brevo will recieve the full `step.events` array. I explained this in detail over here: https://discord.com/channels/895029566685462578/1200076702731214868/1201423013149675633

**Comment by ludorenzetti** [comment]
Hey @scopsy !
I just sent the PR for doc repo

Tell me if it suits you!

**Comment by scopsy** [comment]
@madebyfabian unfortunately this will require some extra work to be supported with this new proposition :(

**Pull request merged**
