### PR TITLE
feat: Upgraded cypress to latest version

### LINKED ISSUE #4426: [NV-2989] Upgrade cypress to latest version
### What?
Upgrade cypress for the following project:
- apps/web
- apps/widget

### Definition of Done
- Test suite is passing on those projects

<sub>[NV-2989](https://linear.app/novu/issue/NV-2989/upgrade-cypress-to-latest-version)</sub>

### PR DESCRIPTION
**Pull request by harsh-solanki21**
### What change does this PR introduce?

This PR upgrades Cypress to the latest version from version `12.17.2` to `13.3.0`

Closes #4426

### CODE REVIEW

**Comment by scopsy** [comment]
@harsh-solanki21 you are missing the pnpm lock file changes here

**Comment by harsh-solanki21** [comment]
@scopsy pnpm lock file changes committed. Thanks for pointing it out 🙏

**Comment by harsh-solanki21** [comment]
@scopsy would you please guide me about what can I do for these failing, cancelled and skipped checks?

**Comment by scopsy** [comment]
@harsh-solanki21 have you run those tests locally? Seems like they are failing due to the version upgrade. 
```
Running:  activities-page.spec.ts                                                        (1 of 29)

Oops...we found an error preparing this test file:

  > cypress/support/e2e.ts

The error was:

Error: Webpack Compilation Error
Module not found: Error: Can't resolve 'process/browser.js' in '/home/runner/work/novu/novu/libs/shared/dist/esm/config'

Module not found: Error: Can't resolve 'process/browser.js' in '/home/runner/work/novu/novu/libs/shared/dist/esm/config'

Cannot read properties of undefined (reading 'module')

Cannot read properties of undefined (reading 'module')
    at handle (/home/runner/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-preprocessor/dist/index.js:212:23)
    at finalCallback (/home/runner/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:441:32)
    at /home/runner/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:505:17
    at /home/runner/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/home/runner/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/runner/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/tapable/lib/Hook.js:18:14)
    at Cache.storeBuildDependencies (/home/runner/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/webpack/lib/Cache.js:122:37)
    at /home/runner/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:501:19
    at Hook.eval [as callAsync] (eval at create (/home/runner/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/runner/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/tapable/lib/Hook.js:18:14)
    at /home/runner/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:498:23
    at Compiler.emitRecords (/home/runner/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:919:5)
    at /home/runner/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:490:11
    at /home/runner/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:885:14
    at Hook.eval [as callAsync] (eval at create (/home/runner/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/runner/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/tapable/lib/Hook.js:18:14)
    at /home/runner/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:882:27
    at /home/runner/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/neo-async/async.js:2818:7
    at done (/home/runner/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/neo-async/async.js:3522:9)
    at Hook.eval [as callAsync] (eval at create (/home/runner/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/runner/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/tapable/lib/Hook.js:18:14)
    at /home/runner/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:736:33
    at /home/runner/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/graceful-fs/graceful-fs.js:143:16
    at /home/runner/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/@packages/server/node_modules/graceful-fs/graceful-fs.js:143:16
    at /home/runner/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/@packages/server/node_modules/graceful-fs/graceful-fs.js:143:16
    at /home/runner/.cache/Cypress/13.3.0/Cypress/resources/app/node_modules/@packages/server/node_modules/graceful-fs/graceful-fs.js:[61](https://github.com/novuhq/novu/actions/runs/6468739525/job/17561854055?pr=4479#step:15:62):14
    at FSReqCallback.oncomplete (node:fs:1[92](https://github.com/novuhq/novu/actions/runs/6468739525/job/17561854055?pr=4479#step:15:93):23)

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.
```

**Comment by harsh-solanki21** [comment]
@scopsy I'll run those tests locally again if these tests are failing there too. 👍

**Comment by scopsy** [comment]
Closing as resolved 🙏

**Pull request closed without merging**
