### PR TITLE
fix: Fixed highlighting hints when hovering on main part

### PR DESCRIPTION
**Pull request by DarkPheonix12**

### CODE REVIEW

**Comment by DarkPheonix12** [comment]
Hey, I have already made change in code as required. Please verify it once!!

**Comment by scopsy** [comment]
@DarkPheonix12 what issue is this PR solved?

**Comment by DarkPheonix12** [comment]
> @DarkPheonix12 what issue is this PR solved? 

I have resolved the issue of hints of not being highlighted when hovering over the main parts they are linked with. Now they are being highlighted when you hover over them.

**Comment by LetItRock** [comment]
hi @DarkPheonix12! 👋 thanks for the contribution 🤝
We do value your time and effort, but we would like to give everyone a fair chance to contribute to our repository.
If the person who was assigned to the original ticket submits the PR we will prefer that one, instead of yours. But if the person won't be able to submit the PR or will be unresponsive we will revisit your PR.
For now, I'm closing it.

The ref issue is I guess https://github.com/novuhq/novu/issues/4249

**Pull request closed without merging**
