### PR TITLE
Add widget user origin wildcard

### PR DESCRIPTION
**Pull request by djabarovgeorge**

### CODE REVIEW

**Comment by davidsoderberg** [comment]
Looks good :), Can we test that cors function?

**Review by davidsoderberg — APPROVED** [review]
🎉

**Comment by djabarovgeorge** [comment]
Tested it locally, while removing the current logic of: 
['dev', 'test', 'local'].includes(process.env.NODE_ENV)

Which blocked the request, and after adding the: 
isWidgetRoute(req.url)
It passed.

**Comment by davidsoderberg** [comment]
Can we create a unit test for it?

**Comment by djabarovgeorge** [comment]
Currently, I will merge and add a task in order to add a test.

**Pull request merged**
