### PR TITLE
Update Novu to Node 18 LTS

### LINKED ISSUE #1959: 🚀 Feature: Update to current active version of Node (18)
### 🔖 Feature description

This Issue is to discuss and track the progress of updating to the next LTS version of node.

### 🎤 Why is this feature needed ?

This will allow the platform to gain from underlying improvements to the ecosystem on top of being in support for 2+ years.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

_No response_

### PR DESCRIPTION
**Pull request by raikasdev**
### What change does this PR introduce?

This PR updates the project to use Node 18 everywhere.

### Why was this change needed?

Closes #1959 

The only currently supported version, Node 16 LTS has it's **end-of-life on September 11th 2023**, about three weeks away now. 

### Other information (Screenshots)

Probably should be discussed if the project should add support up to version 20, which is currently active and will become LTS soon. I will happily make any changes necessary.

All docker container image tag changes have been checked to exist.

Currently this PR sets the node version requirement to `>=18.17.1 <19`, meaning it accepts the current latest LTS patch or a later patch in 18.x, but not versions with a older or a newer major (19, 20).

### CODE REVIEW

**Comment by Cliftonz** [comment]
@raikasdev Thanks for this PR, I can not speak to the failing tests but there is some updated spell checks that need to be updated.

**Comment by raikasdev** [comment]
Oh, some containers might be missing make or something. Will have to investigate on monday when I'm back at home, thanks for pointing out!

**Comment by raikasdev** [comment]
I could not find anything that should have broken those tests. In the E2E tests the servers are starting according to the logs, and in the build Docker API seems to be due to PRs from forks using dockerx instead of Depot used for non-forks (resulting in it succeeding for maintainers and seeming like it's working :shrug:)

**Comment by Cliftonz** [comment]
@raikasdev Thanks for responding. The one thing that is failing but can easily be fixed is the Spell Check CI. All you need to do is add the names to the .cspell file.

**Comment by Cliftonz** [comment]
@djabarovgeorge @LetItRock Would you be able to help with the failing pipelines?

**Comment by raikasdev** [comment]
All failing pipelines seem to be due to missing environmental values (new relic on e2e_web) and not using Depot for the docker API images (due to PR coming from outside repo).

**Comment by scopsy** [comment]
reopening this in another PR to run properly the tests

**Pull request merged**
