### PR TITLE
NV-3665 - 🚀 Feature: add markAsRead markAllUnreadAsRead & markAllUnseenAsSeen in @novu/node

### PR DESCRIPTION
**Pull request by gitstart**
### What change does this PR introduce?
This PR  exposes more APIs (markAsRead, markAllUnreadAsRead & markAllUnseenAsSeen) from widget controllers inside @novu/node.

 ### Why was this change needed?
 So we can have more control on notification outside webapp.
closes https://github.com/novuhq/novu/issues/3665

### Other information

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

### CODE REVIEW

**Review by ainouzgali — CHANGES_REQUESTED** [review]
@gitstart You would also need to add the new functions to subscriber.interface.ts

**Comment by gitstart** [comment]
@ainouzgali Thanks for the review! All the corrections have been made.

**Comment by LetItRock** [comment]
hey, @gitstart 👋 Thank you for your contribution here. 
The changes that you did might overlap with the ones that I'm working on rn and we want to implement this functionality in a slightly different way. Sorry about saying this that late, but from here I'm taking this on me.

**Comment by gitstart** [comment]
All good @LetItRock 🙏. Glad still to have given it a go 😅

**Comment by LetItRock** [comment]
> All good @LetItRock 🙏. Glad still to have given it a go 😅

thank you for your understanding! ❤️

**Pull request closed without merging**
