### PR TITLE
feat: add exception throw on invalid subscriber id

### PR DESCRIPTION
**Pull request by djabarovgeorge**
### What change does this PR introduce? 

fix when API user provides an invalid subscriber id

### Why was this change needed?

in order to get a more informative response from the API.

### CODE REVIEW

**Comment by scopsy** [comment]
@djabarovgeorge the failing test might be related to caching?

**Review by LetItRock — APPROVED** [review]
looks good! it would be nice if you can cover it with the test :)

**Comment by djabarovgeorge** [comment]
> @djabarovgeorge the failing test might be related to caching?

Not this time I will create separate PR in order to fix it, the problem is with the send message base I created.

**Comment by djabarovgeorge** [comment]
> looks good! it would be nice if you can cover it with the test :)

Sound like a good idea. :)

**Comment by djabarovgeorge** [comment]
Hey @scopsy if this one is approved let's merge it.
the failed test here was really flaky one and is fixed on https://github.com/novuhq/novu/pull/2325

**Pull request merged**
