### PR TITLE
fix: api script for e2e tests in root package.json

### PR DESCRIPTION
**Pull request by jainpawan21**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
   fix: update api script for e2e
- **Why this change was needed?** (You can also link to an open issue here)
   With current scripts e2e test does not start
- **Other information**:
 https://discord.com/channels/895029566685462578/1023616359051042827/1023640545312112671

### CODE REVIEW

**Comment by florian-lefebvre** [comment]
I fixed it in https://github.com/novuhq/novu/pull/1292

**Review by p-fernandez — APPROVED** [review]
Looks fine!

@jainpawan21 could you add @florian-lefebvre as co-author?

**Comment by jainpawan21** [comment]
Oh I see, florian has also fixed this in a PR,
@p-fernandez Shall I close this PR then?

**Comment by scopsy** [comment]
Also made a small change on @florian-lefebvre  PR as well, because this command was used in CI to start the API server. I've separated the CI flows to use the "start:api:test" command. It's quite confusing, agree on that. 

Maybe in the future, we can refactor the test running scripts for easier access.

**Pull request merged**
