### PR TITLE
Use node user instead of root user

### LINKED ISSUE #4480: 🐛 Bug Report: Node user instead of root user in Dockerfiles
### 📜 Description

For security reasons, it would be great to use the node user (`1000`) instead of the root user in the Dockerfiles

Either switch to node user before the actions take place in the dockerfiles

```
USER 1000
```

Or set the permissions for the current folder to the node user and switch user at the end of the dockerfiles

```
RUN chown -R 1000:1000 .

USER 1000
```

### 👟 Reproduction steps

Build docker image

### 👍 Expected behavior

Node user (`1000`) should be used instead of root user

### 👎 Actual Behavior with Screenshots

Folder permissions are not set for node user

### Novu version

0.19.0

### npm version

_No response_

### node version

_No response_

### 📃 Provide any additional context for the Bug.

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by mictrax**
### What change does this PR introduce?

The node user (1000) and the corresponding folder permissions are used instead of the root user in the Dockerfile for the web container.

### Why was this change needed?

As described in https://discord.com/channels/895029566685462578/1151776914059571220, this is a known issue and it can be fixed by this permission grant and user switch.

Closes #4480

### Other information (Screenshots)

none

### CODE REVIEW

**Comment by djabarovgeorge** [comment]
Hey @mictrax, thanks for taking the time in order to contribute to the web container image 
@Cliftonz Due to my lack of knowledge in containers would love to hear your opinion on this.

**Comment by Cliftonz** [comment]
@mictrax I understand that this needs looked at however I will not have the time for this in the next few weeks.
I am going to put this in my backlog and get to it as soon as possible.
I am sorry for the inconvenience.

**Comment by AliaksandrRyzhou** [comment]
Hi @mictrax I think it will be better to use `--chown` option of Docker's COPY command instead of  using `RUN chown -R`. `RUN chown -R` usually increase build time and an image size depending on file counts.

**Comment by mictrax** [comment]
Hi @AliaksandrRyzhou 
Thanks for the review. Can you just link the new PR where you will add the node user instead of root for all the containers with this PR?

**Comment by AliaksandrRyzhou** [comment]
Hi @mictrax I've created the PR [5084](https://github.com/novuhq/novu/pull/5084)

**Pull request closed without merging**
