### PR TITLE
Docs Feedback: js code in update-subscriber method has syntax issues

### LINKED ISSUE #4861: 📚 Docs Feedback: js code in update-subscriber method has syntax issues
### Duplicates

- [X] I have searched the existing issues

### Related page

https://github.com/novuhq/novu/tree/next/packages/node#update-a-subscriber

### Kind of issue

Broken demonstration

### Issue description

I was looking at the update subscriber method and it appears has syntax issues

### Context 🔦

Fix Syntax Issues

### PR DESCRIPTION
**Pull request by Atharva1723**
### What change does this PR introduce?

location: https://github.com/novuhq/novu/tree/next/packages/node#update-a-subscriber

### Why was this change needed?

Resolves #4861 

### Other information (Screenshots)
Before:
image

After:
image

### CODE REVIEW

**Comment by jainpawan21** [comment]
@Atharva1723 

Thanks for pointing it out

Please update this method code snippet as well
https://github.com/novuhq/novu/tree/next/packages/node#bulk-create-subscribers

**Review by jainpawan21 — CHANGES_REQUESTED** [review]
Please check create bulk subscriber method as well

**Comment by Atharva1723** [comment]
> Please check create bulk subscriber method as well

Done

**Review by jainpawan21 — APPROVED** [review]

**Comment by Atharva1723** [comment]
@jainpawan21 just now again reviewed similar syntax issue in the https://github.com/Atharva1723/novu/tree/update_node_package/packages/node#trigger-workflow-to-one-subscriber

**Pull request merged**
