### PR TITLE
NV-2194 - 🚀 Feature: Ability to discard a Change

### PR DESCRIPTION
**Pull request by gitstart**
### What change does this PR introduce?
This feature gives users the ability to delete changes from the changes table. 

 ### Why was this change needed?
Closes: https://github.com/novuhq/novu/issues/3311

### Other information

[Loom Video](https://www.loom.com/share/92da2ab901c441038f967d537ea640a7?sid=d284e1b9-0a67-4286-8e2a-bf7d51cb8a1a)

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

### CODE REVIEW

**Comment by michaldziuba03** [comment]
@gitstart I think you referenced wrong issue. 

I guess it shoud be: https://github.com/novuhq/novu/issues/3311

**Comment by jainpawan21** [comment]
> @gitstart I think you referenced wrong issue.
> 
> I guess it should be: #3311

Updated

**Comment by gitstart** [comment]
@scopsy this PR is ready for review

**Review by ainouzgali — COMMENTED** [review]
@gitstart thanks for your hard work. I'm afraid it is more complicated than that. 
While you are deleting the change itself, the content of the change(for example, changes to a workflow) will not be discarded and still exist in dev env. So any other future change in that workflow will be inconsistent as it will build on current content. 

Another issue is that you are deleting one change id, but that represents and depends on other parent changes. So if you delete the one from the table, I believe it would just delete one, and still show the children changes. 
 
Also, some changes are actually aggregated, and includes multiple separate entities changes. For example - creating a notification group that is immediately used in a workflow - will have one row change for both. 

In my opinion, this should be carefully planned before executing. Maybe the right thing is to wait for the team and add to the roadmap. @scopsy what do you think?

**Comment by scopsy** [comment]
@ainouzgali I totally aggree here that there are just too many moving items for simply deleting the change. As It might affect some other underlying changes once the entity will be removed. We will need to do some deeper investigation before we can go and implement something like this. My suggestion is to close this for the time being until we finalize a proper flow for this. 🙏

**Comment by ainouzgali** [comment]
@gitstart closing this for now. Again, thank you! We appreciate it

**Pull request closed without merging**
