### PR TITLE
fix: fixed font size of created at

### LINKED ISSUE #2743: [NV-1656] ✨ Polishing: Font Sizes are inconsistent
### 📜 Description

The font sizes are inconsistent. I have made a few screenshots:

image
image
image

In general:

1. Table font sizes are very small.
2. Sometimes they are not consistent, why is "Created At" smaller than other columns?
3. Activity feed has several small font sizes (11.2px of the left at "Transaction id" and 12px on the right at "Message Sent")

I would define like 4-5 font sizes and use them just everywhere.

### 👟 Reproduction steps

_No response_

### 👍 Expected behavior

_No response_

### 📃 Provide any additional context for the Bug.

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

<sub>[NV-1656](https://linear.app/novu/issue/NV-1656/✨-polishing-font-sizes-are-inconsistent)</sub>

### PR DESCRIPTION
**Pull request by ayush4345**
### What change does this PR introduce?

image
fixed font size of CreatedAt to 14px similar font size of rest of columns which was earlier 12px

### Why was this change needed?

Closes #2743

### CODE REVIEW

**Review by scopsy — APPROVED** [review]
Amazing! Thank you <3

**Comment by scopsy** [comment]
@ayush4345 not yet, will finalize with failing tests and then will merge. We have some flaky tests issues at the moment

**Comment by ayush4345** [comment]
Do you know why tests are failing. Earlier 2 test failed and now it is 3

**Comment by jainpawan21** [comment]
I rerun the test. Now all tests are passing!
Can we now merge this @scopsy

**Pull request merged**
