### PR TITLE
feat: add list item prop to popover notification center

### PR DESCRIPTION
**Pull request by davidsoderberg**

### CODE REVIEW

**Comment by scopsy** [comment]
Will take a look in a bit, could you please also add a section on the docs page for it aswell 🙏

**Comment by davidsoderberg** [comment]
> Will take a look in a bit, could you please also add a section on the docs page for it aswell 🙏

Sure in what section should I do it or should I create a new one for the custom component props on the react components page?

**Comment by scopsy** [comment]
@davidsoderberg you can add the prop to the current props table if there is such, and also section at the bottom of the page something like: "Custom Notification Item component"

**Review by scopsy — APPROVED** [review]
This is awesome, and really useful!

**Pull request merged**
