### PR TITLE
feat(provider): [NV-2961] Add Google Chat Chat Provider #4381

### PR DESCRIPTION
**Pull request by Sushmitha-93**
### What change does this PR introduce?

Adds the Google Chat Provider.

Referred the following Google chat webhook documentation
[Google Chat Webhook](https://developers.google.com/chat/how-tos/webhooks)

### Why was this change needed?

Closes https://github.com/novuhq/novu/issues/4381

### Other information (Screenshots)

Integration-stores

Google chat workflow

build-successful

### CODE REVIEW

**Comment by Sushmitha-93** [comment]
https://github.com/novuhq/novu/pull/4453#issuecomment-1752357275
Screenshot of how it looks after setting line 34 to true in useFeatureFlags file.

Integration-store-with-useFeatureFlag-line34-true

**Comment by Sushmitha-93** [comment]
Hi, I see some test cases to have failed. If there is anything I can l look into to resolve, I would love to help.

**Comment by jainpawan21** [comment]
@LetItRock 
Could you please suggest fix for this failing test
https://github.com/novuhq/novu/actions/runs/7951012540/job/21703985707?pr=4497

**Comment by scopsy** [comment]
Closing due to inactivity, feel free to reopen 🙏

**Pull request closed without merging**
