### PR TITLE
feat: add nextjs with novu integration example

### LINKED ISSUE #2447: [NV-1519] 🚀 Feature: Next.js + Novu Integration Example
### 🔖 Feature description

Add a new project under `/examples` to demonstrate how to use Novu with the latest Next.js (v13). Perhaps, another one strictly with React.

### 🎤 Why is this feature needed ?

To start off, it's something that I believe is just something good to have.

Previously, the Vue and Angular examples only demonstrated the client-side stuffs (notification center components in particular). Next, being as awesome as it is, would allow us to demonstrate how to use the notification center package for React + demonstrate how to use the @novu/node package as well using Next's API routes.

### ✌️ How do you aim to achieve this?

So here's the plan:

- The usual frontend demo on the Notification Center for React (@novu/notification-center).
- An API endpoint `/api/hello` that triggers a notification template.
- The README for the project setup would also have this bonus step on how to set up a Notification Template for he 2nd step (another win 🥳)

### 🔄️ Additional Information

I already have something prepared, here's a screencast on how it works. It's based on the default Next.js 13 starter.

image

Screenshot from 2023-01-08 21-51-57

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

<sub>[NV-1519](https://linear.app/novu/issue/NV-1519/🚀-feature-nextjs-novu-integration-example)</sub>

### PR DESCRIPTION
**Pull request by ShaneMaglangit**
### What change does this PR introduce?

Close #2447 

Adds a new project under /examples that demonstrate how to integrate Novu with the latest Next.js release (v13) -- with the new /app directory.

Packages used:
- @novu/notification-center: Used on the homepage for the notification center component.
- @novu/node: Used by /api/hello to trigger a notification template.

### Why was this change needed?

There are no existing projects under /example for React / Next. Additionally, none demonstrated how to use @novu/node.

### Other information (Screenshots)

image
image
image

### CODE REVIEW

**Comment by LetItRock** [comment]
hey @ShaneMaglangit 👋 
Thank you for your contribution, in the near future we plan to move the examples folder into a separate repository. 
For now, let's maybe have this open for a while and we will ping you when we start moving the examples.

**Comment by scopsy** [comment]
@unicodeveloper where do you think it's best to have this pr merged to?

**Comment by jainpawan21** [comment]
@ShaneMaglangit 
Sorry for your inconvenience
Can you please add this example to [this repo](https://github.com/novuhq/examples) ?

**Comment by ShaneMaglangit** [comment]
Oh sorry, I totally forgot about this one. @p-fernandez @jainpawan21 I currently do not have the capacity to work on this right now, can this be assigned to someone else?

**Comment by scopsy** [comment]
Surething @ShaneMaglangit 🙏 Closing the PR for now due to inactivity.

**Pull request closed without merging**
