### PR TITLE
fix: reinitiate token on page load

### PR DESCRIPTION
**Pull request by scopsy**
Currently jwt is not refreshed when expired

### CODE REVIEW

**Comment by scopsy** [comment]
@djabarovgeorge Can we achieve this like this? Or there was another reason behind it?

**Comment by djabarovgeorge** [comment]
@scopsy  I am not sure in what state of the project, but there was a race condition that caused the Initialize request to take place too many times. however there were a lot of changes on the last version and if it works then I see no problem with it, did you had a chance to test it?

**Comment by scopsy** [comment]
Yes, the `api.isAuthenticated` will avoid the duplicate calls created on the server.

**Review by djabarovgeorge — APPROVED** [review]
🚀

**Pull request merged**
