### PR TITLE
Added translation for a word in Azerbaijani 

### PR DESCRIPTION
**Pull request by Atharva1723**
### What change does this PR introduce?

It adds one more word for the translation to Azerbaijani

### Why was this change needed?

Because the settings word was not translated into Azerbaijani

1) The current translated word is 'Qəbulu' that is referring to Acceptance but instead, it should be 'Parametrlər'

### CODE REVIEW

**Comment by Atharva1723** [comment]
@p-fernandez Please review this PR

**Comment by Atharva1723** [comment]
@p-fernandez Please review this PR

**Comment by Atharva1723** [comment]
@p-fernandez Please review this PR

**Comment by ainouzgali** [comment]
@Atharva1723 are you a native speaker?

**Comment by Atharva1723** [comment]
No, but a friend of mine does and I have referred to multiple translators and have cross-checked and I have also referred to the old  Azerbaijani typescript file ... You too can cross-verify

**Comment by Atharva1723** [comment]
@ainouzgali Can you please review this PR ?

**Comment by jainpawan21** [comment]
@Atharva1723 

As suggested by Gali, we only accept translation PR from native speakers

**Review by jainpawan21 — APPROVED** [review]

**Pull request merged**
