### PR TITLE
Fix/ Made UI changes for tenant

### LINKED ISSUE #4248: [NV-2880] 🏘️ [Tenant] Update layout of the tenant card
## What?
- Creation dialogue on the right-side panel
- Tenand card on the right-side panel

## Why? (Context)
We shipped some UI updates for multiple side cards in the product (such as provider card etc.), so we want to update the tenant card UI to make it consistent with other 

## Definition of Done
- The with of the card is updated for both creation dialogue and a tenant card
- Update button goes to the top of the card of a tenant
- Updated at and Created at info go to the top of the card of a tenant
- The icon "Create tenant" is added to a creation card (see creation dialogue)
- The icon "Tenant" is added to a Tenant card (see tenant card)
- Icon "X close" is updated
- Update space between the header and the content on the tenant card
- The hint on hover of the disabled button should display text in 2 lines (see mock)

**Designs:**
[Tenant list / Creation dialogue](https://www.figma.com/file/Fyc0HATprjA7trYf1PhSOE/Tenants?type=design&node-id=2271%3A27407&mode=design&t=d6qL9EtH1g7nzQGP-1)
[Tenant list / Creation dialogue](https://www.figma.com/file/Fyc0HATprjA7trYf1PhSOE/Tenants?type=design&node-id=2271%3A27474&mode=design&t=d6qL9EtH1g7nzQGP-1)

### PR DESCRIPTION
**Pull request by TheNatkat**
### What change does this PR introduce?

 i have made multiple UI changes in tenant components 

### Why was this change needed?

this chenges are needed because of new figma design

Closes #4248 

### Other information (Screenshots)

figma design -> 

fixed ->

The with of the card is updated for both creation dialogue and a tenant card
previous :
image
new:
image

1) Update button goes to the top of the card of a tenant
2) Updated at and Created at info go to the top of the card of a tenant
3) The icon "Tenant" is added to a Tenant card (see tenant card)
image

4) The icon "Create tenant" is added to a creation card (see creation dialogue)
5) Update space between the header and the content on the tenant card
image

6)The hint on hover of the disabled button should display text in 2 lines (see mock)
image

### CODE REVIEW

**Comment by scopsy** [comment]
@TheNatkat thank you so much for the contribution, from a very quick look, seems like the update button at the top is offset at the wrong position (right margin) please look at the design which is aligned to the "X" button.

In general could you review figma designs to align in terms of spacing?

**Comment by TheNatkat** [comment]
@scopsy hi, i know the update button should come below the x close button but because of the component sidebar i am not able to do that (as x close button is a part of sidebar) to make it exactly like figma designs i have to edit the sidebar component and if i did that then sidebar component is also used in other places and it replace that also. but i will try to fix it if i am able do that i will merge it.

**Comment by TheNatkat** [comment]
image

I fixed the position on update button @scopsy

**Comment by TheNatkat** [comment]
image

I fixed the position on update button @scopsy

**Comment by TheNatkat** [comment]
hi, team is there any changes to be done from my side?

**Comment by scopsy** [comment]
@ainouzgali could you help with a check here?

**Comment by ainouzgali** [comment]
@TheNatkat after we finish with your delete tenant PR we will get into this one :)

**Comment by TheNatkat** [comment]
@ainouzgali, I apologize, but I'm new to open source contributions, and I believe I should delete this pull request and create a new one specifically for the UI updates. This pull request includes changes in 4 files, and it also involves the delete tenant update.

**Comment by TheNatkat** [comment]
hi  team there is there any issue in from my side

**Pull request closed without merging**
