### PR TITLE
NV-1327 i18n - Odia Support

### PR DESCRIPTION
**Pull request by Rutam21**
- **What kind of change does this PR introduce?**
  This PR adds the Odia Language support for Novu

- **Why this change was needed?**
  This PR fixes https://github.com/novuhq/novu/issues/1327.

### CODE REVIEW

**Comment by Rutam21** [comment]
@scopsy @davidsoderberg @ainouzgali Please review and approve. Also, it would be great if you could please add the `hacktoberfest-accepted` label once it is approved. Thanks.

**Comment by scopsy** [comment]
@Rutam21 could you please merge latest changes?

**Comment by Rutam21** [comment]
@scopsy I have resolved the merge conflicts. You can proceed with the merge now.

**Review by scopsy — APPROVED** [review]
Thank you!

**Pull request merged**
