### PR TITLE
refactor: use date-fns instead of moment

### PR DESCRIPTION
**Pull request by venarius**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Replaces moment for date-fns for the whole repo

### CODE REVIEW

**Comment by venarius** [comment]
Seems that everytime I run ```pnpm i``` inside the basefolder after changing dependencies it seems to break the whole CI. Same as in my other PR https://github.com/novuhq/novu/pull/1115

```bash
ubuntu@hydrogen:~/Workspace/novu$ pnpm -v
7.9.3
```

Does someone maybe know why? 😅

**Comment by djabarovgeorge** [comment]
Hey @venarius try to run `pnpm install`
and push the updated pnpm lock file.

**Comment by venarius** [comment]
image

@djabarovgeorge it just says that everything is okay 😅

**Comment by scopsy** [comment]
@venarius Could you try using 7.5.0 of pnpm? we use it for ou caches, maybe it has something to do with it

**Comment by venarius** [comment]
@scopsy Yes, that did the trick! Seems like newer versions of pnpm do not work right now. Thank you 😊

**Review by scopsy — APPROVED** [review]
Great to remove all moment dependencies 🎉 will look on the merge conflicts so we can merge

**Pull request merged**
