### PR TITLE
feat: implement #1781

### PR DESCRIPTION
**Pull request by MaximFedarau**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Implement #1781.

- **Why was this change needed?** (You can also link to an open issue here)
***The reason has already been mentioned in the issue.***

### CODE REVIEW

**Review by p-fernandez — APPROVED** [review]
🌟

**Comment by MaximFedarau** [comment]
@scopsy, @p-fernandez But it fails test, which is not connected with my feature.🤨

**Review by florian-lefebvre — APPROVED** [review]

**Comment by scopsy** [comment]
@MaximFedarau could you please attach an image from the web panel here just to make sure that the location of the logo hasn't change due do this?

**Comment by MaximFedarau** [comment]
@scopsy Tested 2 cases:
- ### Desktop:

https://user-images.githubusercontent.com/87207122/196954022-0e27e6fc-6b00-451c-8607-14393e4e5b5f.mov

- ### Mobile (Galaxy Fold):

https://user-images.githubusercontent.com/87207122/196954145-cb3a4105-f5c0-4f51-bfd5-09e5d6967426.mov

Everything is 👌.

**Comment by MaximFedarau** [comment]
@scopsy , are these images good?

**Pull request merged**
