### PR TITLE
NV-2060 - 🐛 Bug Report: Incomplete i18n

### PR DESCRIPTION
**Pull request by gitstart**
### What change does this PR introduce?
- Update no-notification image
- Enable the text previously on the image to adapt to various locales.

### Why was this change needed?
Closes: https://github.com/novuhq/novu/issues/3154

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

### CODE REVIEW

**Comment by gitstart** [comment]
@scopsy this PR is ready for review

**Review by LetItRock — APPROVED** [review]
looks good to me! 🌟

**Comment by scopsy** [comment]
@gitstart do you have an image on how the design looks right now with the text there?

**Comment by seunexplicit** [comment]
@scopsy here is a loom video of the current design..

https://www.loom.com/share/eb635bd9963540b4ac8a77910e309dae

**Comment by gitstart** [comment]
@scopsy here is a loom video of the current design..

https://www.loom.com/share/eb635bd9963540b4ac8a77910e309dae

**Pull request merged**
