### PR TITLE
feat: adds cancel button

### PR DESCRIPTION
**Pull request by BhuvaneshPatil**
### What change does this PR introduce?

Adds "Cancel" button to template editing screen.

### Why was this change needed?
#2274 . There was no option to go back to the page. From edit mode which was easily accessible from UI.

image

### CODE REVIEW

**Review by p-fernandez — COMMENTED** [review]
Thanks for this PR. I would ask you to add a Cypress test to check this functionality here:
https://github.com/novuhq/novu/blob/80dec10b86b5a0fe7d8d718dd3a9ab8bafef204c/apps/web/cypress/tests/notification-editor/main-functionality.spec.ts#L3

**Comment by BhuvaneshPatil** [comment]
> Thanks for this PR. I would ask you to add a Cypress test to check this functionality here:
> 
> https://github.com/novuhq/novu/blob/80dec10b86b5a0fe7d8d718dd3a9ab8bafef204c/apps/web/cypress/tests/notification-editor/main-functionality.spec.ts#L3

Hello @p-fernandez . I wrote the test case but was not able to run it. Pbbly cause of system specs.
```
it('should go to templates on cancel button click', function () {
    const template = this.session.templates[0];
    cy.visit('/templates/edit/' + template._id);
    cy.getByTestId('template-editing-cancel-button').first().click();
    cy.location('pathname').should('equal', '/templates');
  });
```

**Comment by p-fernandez** [comment]
> > Thanks for this PR. I would ask you to add a Cypress test to check this functionality here:
> > https://github.com/novuhq/novu/blob/80dec10b86b5a0fe7d8d718dd3a9ab8bafef204c/apps/web/cypress/tests/notification-editor/main-functionality.spec.ts#L3
> 
> Hello @p-fernandez . I wrote the test case but was not able to run it. Pbbly cause of system specs.
> 
> ```
> it('should go to templates on cancel button click', function () {
>     const template = this.session.templates[0];
>     cy.visit('/templates/edit/' + template._id);
>     cy.getByTestId('template-editing-cancel-button').first().click();
>     cy.location('pathname').should('equal', '/templates');
>   });
> ```

Sorry, what do you mean that you were not being able to run it because system specs? Is the Cypress test runner to heavy for your computer?

**Comment by scopsy** [comment]
Hi @BhuvaneshPatil, really thank you for the initiative. However, we will need to do a re-review of the navigation stack and breadcrumbs in the next couple of cycles. I think that the cancel functionality should be better portrayed as a "Back" button, but the location should be in a different place than it is right now. Unfortunately, we don't have the capacity right now to create the final UX for this page. 

I will close this PR and update you once we have the final UX and design ready for this to be worked on. 🙏

**Pull request closed without merging**
