### PR TITLE
Improved Drag-and-drop reordering of workflow steps

### LINKED ISSUE #3854: [NV-2610] 🏗️ Provide the ability to rearrange steps in a workflow
**What?**

WF editor steps order

**Why?**

Currently, users won't be able to rearrange step orders, so if they make a mistake and put a step into the wrong order, they may just create a new step in the desired place of a workflow. But he needs to fill in all the metadata for that step all over again. We assume that UX where UI prompts users to do double work in case they made a mistake with a steps order might be confusing.

**How?**

Allow users to reorder steps by **drag and drop.**

**MECHANICS**

* User hover over a step
* UI display D&D hover icon near a step
* User clicks on the icon and drags it Up or Down
* When the step becomes closer than distance 8px to its neighbor, they switch places.
* The dragged step takes the place of its neighbor, the neighbor takes the place of a step that was dragged

Example

[Re-order steps - Workflow create/edit (Figma)](https://www.figma.com/file/72BWZJMFf9aikgI7CPpohp/Workflow-create%2Fedit?type=design&node-id=274-53699&mode=design&t=G2ykbLhUeNYYGvOS-4)

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-2610](https://linear.app/novu/issue/NV-2610/🏗️-provide-the-ability-to-rearrange-steps-in-a-workflow)</sub>

### PR DESCRIPTION
**Pull request by madoyi**
Added Reordering Functionality: I added the ability to reorder steps in the workflow. This means you can now drag and drop steps to change their order.

Updated the initializeWorkflowTree Function: I modified the initializeWorkflowTree function to handle building the workflow with the new reordering logic. Now, it uses the swapSteps function from the useTemplateEditorForm hook to adjust the order of steps in response to user drag-and-drop actions.

Added onReorder Prop: I added a new onReorder prop to the FlowEditor component. This prop is a callback function that gets triggered when steps are reordered. It's responsible for updating the order of steps in your workflow data.

Added handleReorderSteps Function: I created a new function called handleReorderSteps in the WorkflowEditor component. This function takes care of handling the reorder action by calling the swapSteps function from the useTemplateEditorForm hook.

Updated FlowEditor Component Props: I updated the props of the FlowEditor component to include the new onReorder prop. This enables the FlowEditor to notify the parent component (WorkflowEditor) when steps are reordered.

Updated WorkflowEditor's handleReorderSteps: I modified the handleReorderSteps function in the WorkflowEditor component to call the onReorder prop of the FlowEditor component when steps are reordered.

Overall, these changes allow you to visually reorder the steps in the workflow editor and save the new order to your data when you save or update the workflow. The user experience is improved by providing an intuitive drag-and-drop mechanism for reordering steps in your workflow.

Closes #3854

### CODE REVIEW

**Comment by ainouzgali** [comment]
Hi @madoyi! Let me know if you need help with updating from next and reopening the PR :)

**Comment by madoyi** [comment]
> Hi @madoyi! Let me know if you need help with updating from next and reopening the PR :) 

Yeah, that would be great

**Comment by ainouzgali** [comment]
To me it seems you didn't push a lot of your logic. Could you please take a look? Like all the hooks you added and the reordering logic.

**Comment by scopsy** [comment]
Closing due to inactivity.

**Pull request closed without merging**
