### PR TITLE
refactor: imports of hooks

### PR DESCRIPTION
**Pull request by davidsoderberg**
### What change does this PR introduce?
Change imports from `**/hooks/use*.*` to `**/hooks`.

### Why was this change needed?
To unify how we import hooks.

### CODE REVIEW

**Review by BiswaViraj — APPROVED** [review]

**Review by p-fernandez — APPROVED** [review]
🌟

**Review by LetItRock — APPROVED** [review]
🔥

**Comment by djabarovgeorge** [comment]
@davidsoderberg i have strange question/request, could you check if get circular dependency alert after you building the project

**Comment by davidsoderberg** [comment]
> @davidsoderberg i have strange question/request, could you check if get circular dependency alert after you building the project

No I have even removed the build folder for web and do not get it...

**Pull request merged**
