### PR TITLE
fix: fix decision of when should create another digest event

### PR DESCRIPTION
**Pull request by ainouzgali**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
fix case of an extra digest created for delayed (regular or scheduled) that comes before digest 

- **Why was this change needed?** (You can also link to an open issue here)
WF:
Screen Shot 2022-10-13 at 11 20 19

Triggering twice resulted in :
image

Now:
image

- **Other information**:

Also fixes the problem:
- that events that are delayed are added to a current digest, before their delay time completed.  
- events that have digest pending being sent twice

### CODE REVIEW

**Review by davidsoderberg — APPROVED** [review]
Looks good to me, the tests is passing without any changes so should be fine 😄

**Review by p-fernandez — APPROVED** [review]
🌟

**Comment by sebastiaanviaene** [comment]
Thanks for fixing this so quickly guys!! Really appreciate it

**Review by scopsy — COMMENTED** [review]
Could you please add some comments or introduce functions so it will be easier to comprehend the flow in the repository or also in the queue service. 

Also, would be great if we will have 2 e2e tests for those 2 edge cases.

**Pull request merged**
