### PR TITLE
feat: add mark all as read functionality

### PR DESCRIPTION
**Pull request by jainpawan21**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
  feature: This pr adds mark all as read functionality in notification-center
- **What is the current behavior?** (You can also link to an open issue here)
#955 
- **What is the new behavior (if this is a feature change)?**
Mark all as read functionality is working ✅

https://user-images.githubusercontent.com/39362422/185638862-948ba7c1-f1e5-4d58-9943-c6a240a9697b.mov

- **Other information**:
Reopened as #1015 is closed

### CODE REVIEW

**Comment by jainpawan21** [comment]
@scopsy Did you get any update from the designer on this?

**Comment by scopsy** [comment]
Yes @jainpawan21 sorry missed your previous comment. The designs are here: https://www.figma.com/file/IpAw7sGWYZ8DHTem0tSM8r/Ready-for-Dev?node-id=2732%3A11226
It's quite similar to what you've done, so just checking the space between texts there

**Comment by scopsy** [comment]
Hi @jainpawan21 just wanted to check in if you had a chance to see the figma designs 🙏

**Comment by jainpawan21** [comment]
> Hi @jainpawan21 just wanted to check in if you had a chance to see the figma designs 🙏

Sorry, I missed this PR 
I will update as per figma design

**Comment by ainouzgali** [comment]
Thank you @jainpawan21 ! This looks great. Will be released at v0.9.0

**Pull request merged**
