### PR TITLE
style(web): Fix add tenant button location

### PR DESCRIPTION
**Pull request by nick2432**
### What change does this PR introduce?

I modified the container padding from 0px 30px 8px 30px to 0px 24px 0px 24px.
Screenshot from 2023-12-04 09-20-19

### Why was this change needed?

Closes https://github.com/novuhq/novu/issues/4886

### Other information (Screenshots)
Screenshot from 2023-12-04 08-58-17

### CODE REVIEW

**Review by scopsy — APPROVED** [review]

**Comment by scopsy** [comment]
Thank you!

**Comment by SebastianStehle** [comment]
I would also check the other buttons, I have seen other, minor differences. But I am not 100% sure anymore.

**Comment by nick2432** [comment]
> I would also check the other buttons, I have seen other, minor differences. But I am not 100% sure anymore.
@scopsy 
can you tell me which one button location is correct
Screenshot from 2023-12-05 16-59-32
Screenshot from 2023-12-05 16-57-47

**Comment by scopsy** [comment]
Sure!

**Pull request merged**
