### PR TITLE
feat: added user-agent to node package

### LINKED ISSUE #4233: [NV-2930] [NV-2792] Add request header to node sdk
## What?
Add request header to node sdk.
Example:

```
headers: {
   Authorization: `Bearer ${ApiKey}`,
   "User-Agent": `novu/node@${version}`,
},
```

## Why? (Context)
Having request headers in the SDKs will help us in monitoring which SDK is mostly used by the community and customers. It will help us make the decision to officially maintain that SDK in the future. We will be able to filter out requests on our API by that header.

## Definition of Done
- include the "User-Agent": "novu/node@${version}" header in all requests from node sdk

### PR DESCRIPTION
**Pull request by FroostyCodes**
## What change does this PR introduce?

Updated the node package to include user-agent header with the current sdk version.

Had to made changes to tsconfig in order to import the package.json (which contains the sdk version).
Removed the rootDir to be just `src` as we needed package.json from outside that directory

Also updated the package.json file to properly select the default file with the new changes to the tsconfig and rootDir

## Why was this change needed?

Closes #4233 

## Other information
Due to some mistake the previous PR (#4321) was closed, so had to open another one

### CODE REVIEW

**Comment by scopsy** [comment]
@LetItRock @rifont I wonder if we might see some unexpected behaviour on the user side due to this change?

**Comment by rifont** [comment]
> @LetItRock @rifont I wonder if we might see some unexpected behaviour on the user side due to this change?

It's possible that the build artifact linking will be impacted, however this has been addressed via changes to `main`, `typings`, and `module`. We should build and publish a mock public NPM package, then test the mock package can be installed and used successfully in a client SDK integration.

@FroostyCodes , would you be able to perform the steps above to test that the package can still be installed correctly? After doing so, could you please share a link to the NPM package for inspection as part of the PR review. Let me know if you have any questions or assistance.

**Comment by FroostyCodes** [comment]
@rifont Sadly I don't have any experience with publishing NPM package, especially in a mono repo.

**Comment by rifont** [comment]
> @rifont Sadly I don't have any experience with publishing NPM package, especially in a mono repo.

No problem, I'm happy to help. You don't need to worry about the publishing the full monorepo, you can simply publish a single package.

You can try these steps to publish and test the package:
1. [Sign up/sign in to NPM](https://www.npmjs.com/signup)
2. Change the `@novu/node` package name in `package.json` to something else, like `FroostyCodes-novu-node`
3. Build the node package with `cd packages/node && pnpm build)
4. Publish the package with `npm publish`. You may be asked to sign into npm from the CLI.
5. Verify the package is available on npm at `https://npmjs.com/package/FroostyCodes-novu-node`
6. Create a sample project, `npm install FroostyCodes-novu-node` and test that the package can be used to successfully invoke the Novu API

Let me know if you need any further assistance.

**Pull request closed without merging**
