### PR TITLE
Added words for Kannada language translation and also changed the language code

### PR DESCRIPTION
**Pull request by Atharva1723**
What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)
It adds two more words for the translation to kannada and changes the actual language code for Kannada

Why was this change needed?
Because settings and no new notification words were not translated into Kannada
And the actual code for kannada language is kn not ka

### CODE REVIEW

**Review by djabarovgeorge — COMMENTED** [review]
Look like there are a couple of mismatches, first of all, the ka stands for Georgian. https://docs.mojolicious.org/I18N/LangTags/List 
You were right to update the code to kn because the translations were in Kannada, however, it looks like you translated noNewNotification in Georgian.
I apologize if I misunderstood something I am not native not in Kannada or Georgian.
Are you a native Kannada speaker?

**Comment by Atharva1723** [comment]
@djabarovgeorge The word no new notification I translated is in Kannada language and yes I speak Kannada at home. If there is a requirement for the Kannada language then this PR can be merged or else I can also create a new one for the Georgian language.

**Comment by Atharva1723** [comment]
@davidsoderberg @djabarovgeorge Can you please review my PR and let me know if any changes are required ?

**Review by djabarovgeorge — APPROVED** [review]
Good work, looks like I translated it wrong before.

**Comment by Atharva1723** [comment]
Can this PR be merged ?@djabarovgeorge @davidsoderberg @nevo-david

**Pull request closed without merging**
