### PR TITLE
chore(docker, workspace-root): update node to lts

### LINKED ISSUE #4501: 🚀 Feature: Bump pnpm version to latest
### 🔖 Feature description

This feature is to bump pnpm version requirement of the project to the latest. The project currently makes use of `7.33` which is outdated.

### 🎤 Why is this feature needed ?

Devs with the latest pnpm version can't install the project due to the strict engine check in the `package.json` file and there have been a lot of performance improvements.

### ✌️ How do you aim to achieve this?

update the engine and package manager section in the package JSON file.
- make the lockfile up-to-date.

### 🔄️ Additional Information

_No response_

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by dammy001**
### What change does this PR introduce?
Update node version to LTS which is v18 || >=20

- Breaking change
@novu/emailjs required node version is now >=12 because of one regression on emailjs package here https://github.com/eleith/emailjs/pull/342 which required bumping the version

### Why was this change needed?
The current node version has reached EOL(no longer been maintained)

This PR #4528 by @scopsy already closes the issue I opened concerning pnpm here #4501 but I'll close it via this PR 

- closes #4501

### CODE REVIEW

**Comment by dammy001** [comment]
@scopsy please check this PR. I'm also thinking we should drop support for node 10 for all public packages and providers packages

**Comment by scopsy** [comment]
Thank you @dammy001, there is an already ongoing PR #4014 

One of the issues we encountered, is how node 18 treats localhost addresses which causes all of our tests to fail there

So we need to change all `localhost` to 0.0.0.0 addresses if I remember correctly

**Comment by scopsy** [comment]
@dammy001 do you mind creating a PR with the emailjs changes against #4556 so we can track progress there?

**Comment by dammy001** [comment]
@scopsy you mean I should close this PR in favour of #4556?

**Comment by scopsy** [comment]
@dammy001 yes, and only cherry pick your changes related to emailjs upgrade 🙏

**Comment by p-fernandez** [comment]
Closing in favour of https://github.com/novuhq/novu/pull/4571

Thank you very much for your help @dammy001

**Pull request closed without merging**
