### PR TITLE
NV-2225 - 🐛 Bug Report: Visual bug - dual scroll in integration configuration modal

### PR DESCRIPTION
**Pull request by gitstart**
### What change does this PR introduce?
Removes double scrolls from integration configuration modal

 ### Why was this change needed?
closes https://github.com/novuhq/novu/issues/3345

### Additional information
[Loom video](https://www.loom.com/share/bc49d52f79764e09a8841a2ad61fa2a2)

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

### CODE REVIEW

**Comment by gitstart** [comment]
@scopsy this PR is ready for review

**Comment by jainpawan21** [comment]
@gitstart can you please add some screen recording how this works?

**Comment by gitstart** [comment]
> @gitstart can you please add some screen recording on how this works?

@jainpawan21 here you go: https://www.loom.com/share/bc49d52f79764e09a8841a2ad61fa2a2

**Review by jainpawan21 — APPROVED** [review]

**Comment by jainpawan21** [comment]
Thanks @gitstart 🤩

**Pull request merged**
