### PR TITLE
fix: remove repeated find statement after notification create

### PR DESCRIPTION
**Pull request by jainpawan21**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
     fix: remove repeated find statement
- **What is the current behavior?** (You can also link to an open issue here)

- **What is the new behavior (if this is a feature change)?**

- **Other information**:

### CODE REVIEW

**Review by scopsy — APPROVED** [review]
Great catch! Looks like definitely not needed here

**Comment by jainpawan21** [comment]
@scopsy fixed failing test cases

**Review by scopsy — APPROVED** [review]
This looks good to me, @davidsoderberg could you also take a look perhaps there was a reason for this duplicate query before. Notice the the `findById` returns a populate fields, don't belive it should affect the `CreateChanges` command but just in case.

**Comment by davidsoderberg** [comment]
Looks good to me 👍

**Review by davidsoderberg — APPROVED** [review]

**Pull request merged**
