### PR TITLE
Add save button for digest

### PR DESCRIPTION
**Pull request by Wyfy0107**
- **What kind of change does this PR introduce?**
Add save button for digest

- **What is the current behavior?**
#1151 
The current form of digest does not have a save button, which is bad UX

- **What is the new behavior (if this is a feature change)?**
Now with a save button, user can save after editing digest properties

- **Other information**:

### CODE REVIEW

**Comment by scopsy** [comment]
Thank you so much for you contribution @Wyfy0107! A small question does the button right now submits the entire form of notification template? If so, can we just submit or persist the changes related to the digest section? Even if we just hide the side bar for the user without doing anything. Just logically it feels more sense for the user to have this button available for him. 

What do you think about that approach? 

P.S 
Could you please add a screen shot of how the button visually looks it will help a lot 🎉

**Comment by Wyfy0107** [comment]
> Thank you so much for you contribution @Wyfy0107! A small question does the button right now submits the entire form of notification template? If so, can we just submit or persist the changes related to the digest section? Even if we just hide the side bar for the user without doing anything. Just logically it feels more sense for the user to have this button available for him.
> 
> What do you think about that approach?
> 
> P.S Could you please add a screen shot of how the button visually looks it will help a lot 🎉

Yes it will submit the entire form currently. I agree it would make more sense to just save digest related data.  I will update it.
Here's the picture currently

Screenshot 2022-08-31 at 23 28 29

**Comment by Wyfy0107** [comment]
@scopsy It looks like there's not dedicated api endpoint for digest as it's a step of notification template. So I guess I will just hide the form for now

**Comment by scopsy** [comment]
Yes @Wyfy0107 exactly, it's just a UI hide functionality 🚀

**Review by scopsy — APPROVED** [review]

**Pull request merged**
