### PR TITLE
fix(fcm): do not mutate overrides object

### LINKED ISSUE #4850: 🐛 Bug Report: FCM push notification overrides are only applied to first device token
### 📜 Description

When sending push notifications with overrides (e.g. setting the type to `data`) to a subscriber with multiple FCM device tokens, only the first registered device will receive the notification with the correct overrides. The first device token might not even be valid anymore, so the notification with the correct overrides might not have been received at all.

Looking at the code it seems that the options object including the overrides is modified in-place, e.g.:
https://github.com/novuhq/novu/blob/947ab956121aebe070342cbc1853d2f81dc89847/providers/fcm/src/lib/fcm.provider.ts#L66

and this code gets called when iterating over the device tokens of the subscriber:
https://github.com/novuhq/novu/blob/947ab956121aebe070342cbc1853d2f81dc89847/apps/worker/src/app/workflow/usecases/send-message/send-message-push.usecase.ts#L165

### 👟 Reproduction steps

```
curl --location --request POST 'https://eu.api.novu.co/v1/events/trigger' \
     --header 'Authorization: ApiKey <REPLACE_WITH_API_KEY>' \
     --header 'Content-Type: application/json' \
     --data-raw '{
         "name": "post-comment-mention",
         "to": {
           "subscriberId": "<ID-OF-SUBSCRIBER-WITH-MULTIPLE-FCM-DEVICE-TOKENS>"
         },
         "payload": {
           "data": {
             "user": {
               "fullName": "Test SF",
             },
           },
         },
         "overrides": {
           "type": "data",
           "fcm": {
             "type": "data",
             "data": {
               "userFullName": "Test SF",
             }
           },
           "apns": {
             "payload": {
               "data": {
                 "user": {
                   "fullName": "Test SF",
                 },
               },
             }
           }
         }
       }'
```

### 👍 Expected behavior

All push notifications for a subscriber with multiple device tokens should be sent with all overrides provided.

Example notification with type `data` set via overrides (currently no message body due to https://github.com/novuhq/novu/issues/4639)

notification_expected

### 👎 Actual Behavior with Screenshots

Example notification that should have been sent with type `data` set via overrides (expected no message body due to https://github.com/novuhq/novu/issues/4639)

notification_received

### Novu version

Novu SaaS

### npm version

_No response_

### node version

_No response_

### 📃 Provide any additional context for the Bug.

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by strangeAeon**
### What change does this PR introduce?

This PR changes how values from the `overrides` passed to the FCM provider are extracted without mutating the object.

### Why was this change needed?

Closes #4850

### CODE REVIEW

**Review by scopsy — APPROVED** [review]
Thank you for the contribution!

**Comment by strangeAeon** [comment]
hi @scopsy!
some of the e2e-tests seem to be flaky: i ran the tests locally and the same test cases that failed in the ci-pipeline ran successfully for me (while others did not). i'm also not sure how my fcm-specific changes could have an influence on those tests.
so is it possible to merge my pr regardless of the failing e2e tests? or can you give me hints what i would have to adjust? thanks in advance!

**Comment by scopsy** [comment]
@strangeAeon I don't believe they are related :( Trying to re run them again

**Comment by scopsy** [comment]
@strangeAeon could you please merge from latest next? I believe it should address the tests 🙏

**Comment by strangeAeon** [comment]
@scopsy one e2e test is still failing :/ can you re-run them again? or are there again updates related to tests on next that i should merge?

**Comment by scopsy** [comment]
This is not related to the PR. Merging this 🙏

**Pull request merged**
