### PR TITLE
feat(spotlight): add navigation to integrations in the command palette

### LINKED ISSUE #1341: [NV-935] - Add navigation to Integrations in command palette
**Why**

To make the navigation even easier we need to add it to the command palette… 

**How**

This should be done in a global place but inside of the SpotLightProvider or inside of the Spotlight.tsx file.

To do this we need to add following: (example exists inside of Spotlight.tsx)

```
{
  id: 'navigate-templates',
  title: 'Go to Notification Template',
  onTrigger: () => navigate('/templates'),
  icon: <Bolt />,
}
```

Please note that navigate comes form `react-router-dom` …

Id needs to be unique for every command and needs to be clear what it is doing.

Icon should be the same as in the main menu.

If it is added from a global place, `addItem` function from `SpotlightContext` can be used just pass the object to that method inside of an useEffect without any dependencies.

### PR DESCRIPTION
**Pull request by nidble**
[NV-935] - Add navigation to Integrations in the command palette

fix #1341

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Add new navigation to Integrations as described in [NV-935]
- **Why was this change needed?** (You can also link to an open issue here)
#1341

### CODE REVIEW

**Review by scopsy — APPROVED** [review]
Thank you so much for your contribution! Really appreciate it 🙏

**Comment by nidble** [comment]
It was a pleasure, thank to you also for this opportunity!

**Comment by jainpawan21** [comment]
@scopsy It is strange that e2e_web_tests are failing with this change

**Comment by ainouzgali** [comment]
The tests failed from an unrelated problem😅 Thank you for your contribution @nidble !

**Pull request merged**
