### PR TITLE
Docs Feedback: js code in create-subscriber method has syntax issues

### LINKED ISSUE #4706: 📚 Docs Feedback: js code in create-subscriber method has syntax issues
### Duplicates

- [X] I have searched the existing issues

### Related page

https://docs.novu.co/api-reference/subscribers/create-subscriber

### Kind of issue

Broken demonstration

### Issue description

I was looking at the create subscriber method and it appears has syntax issues

reference issue: https://github.com/novuhq/docs/issues/311#issuecomment-1784588027

### Context 🔦

Fix Syntax Issues

### PR DESCRIPTION
**Pull request by codingis4noobs2**
### What change does this PR introduce?
location: https://github.com/novuhq/novu/tree/next/packages/node#identify-create-a-new-subscriber
The code has syntax issues, so I fixed those issues

### Why was this change needed?
Closes #4706 

### Other information (Screenshots)
Before:
image

After:
image

### CODE REVIEW

**Review by BiswaViraj — APPROVED** [review]

**Comment by codingis4noobs2** [comment]
Hey @BiswaViraj , I am not sure about the failed docker tests
it will be helpful if you could guide me 🙇‍♂️

**Comment by BiswaViraj** [comment]
Hello @codingis4noobs2, you can ignore the docker test. It fails for every PR through a fork repository.
You don't need to do anything now. I will merge this PR after some time.
Thank you for the PR 🚀

**Comment by codingis4noobs2** [comment]
Thank you 🙏

**Comment by codingis4noobs2** [comment]
@BiswaViraj if you don't mind, can you please add hacktoberfest tag 🙂

**Comment by BiswaViraj** [comment]
@codingis4noobs2 Adding it 😇

**Pull request merged**
