### PR TITLE
fix : responsive notification center for mobile devices

### PR DESCRIPTION
**Pull request by amitanshusahu**
### What change does this PR introduce?

made the notification center responsive for mobile devices

### Why was this change needed?

see issue #3125 

### Other information (Screenshots)
NA

### CODE REVIEW

**Comment by unicodeveloper** [comment]
@amitanshusahu can you add an image or video to the PR to show how mobile responsive the NC is based on your work?

**Review by LetItRock — APPROVED** [review]
looks good! thanks! 🚀 
Screenshot 2023-04-14 at 13 37 59
Screenshot 2023-04-14 at 13 36 40

**Comment by amitanshusahu** [comment]
hey @LetItRock , i am new to the project and looking forward to contribute more but i am having trouble setting up the project in my machine . It freezes when ever i run `npm run setup:project`.  

you were able to test the changes, can you help me in doing that as well 😅 , or is there any way to test a particular package without running the entire repo

**Comment by LetItRock** [comment]
> hey @LetItRock , i am new to the project and looking forward to contribute more but i am having trouble setting up the project in my machine . It freezes when ever i run `npm run setup:project`.
> 
> you were able to test the changes, can you help me in doing that as well 😅 , or is there any way to test a particular package without running the entire repo

the easiest way to run the whole app is by using our Jarvis CLI tool ;) 
if you just cloned the project from the GH, then you can run `npm run start` in the root folder, then pick what you wanted to do from the options list ;)

**Pull request merged**
