### PR TITLE
Fixed grammatical errors in architecture.md

### PR DESCRIPTION
**Pull request by akshitagupta15june**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Fixed grammatical errors in architecture.md

- **Why was this change needed?** (You can also link to an open issue here)
This change was needed for better readability 
- **Other information**:

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
@p-fernandez @scopsy @davidsoderberg  please review

**Review by davidsoderberg — APPROVED** [review]
Looks good :)

**Comment by akshitagupta15june** [comment]
@davidsoderberg will it be merged automatically?

**Comment by davidsoderberg** [comment]
Nope just waited for the build to finish :)

**Comment by akshitagupta15june** [comment]
@davidsoderberg please review #1527 and #1528

**Review by davidsoderberg — APPROVED** [review]

**Pull request merged**
