### PR TITLE
Added a more meaningful word translation in german typescript file

### PR DESCRIPTION
**Pull request by Atharva1723**
### What change does this PR introduce?

This PR changes a German translation word in de typescript file for the word Powered By

### Why was this change needed?

This change was needed as the word 'Powered By' is translated as 'von' in the current German typescript. But the more meaningful translation for the word is 'Angetrieben von' which translates to 'Powered By' in English

### CODE REVIEW

**Comment by Atharva1723** [comment]
@Cliftonz Please review my PR. Thank you :)

**Comment by Atharva1723** [comment]
@p-fernandez @Cliftonz Can you please review this PR? Thank You :)

**Comment by sumitsaurabh927** [comment]
Are you a native German speaker. We only accept translation PRs from native speakers.

**Comment by Atharva1723** [comment]
> Are you a native German speaker? We only accept translation PRs from native speakers.

I am fluent  in German language and I have referred to multiple translators and have cross-checked and I have also referred to the old German typescript file ... You too can cross-verify

**Comment by sumitsaurabh927** [comment]
Closing this as @Atharva1723 has confirmed that he's not a native speaker.

**Pull request closed without merging**
