### PR TITLE
i18n - Punjabi Support

### PR DESCRIPTION
**Pull request by ArmanChand**
What kind of change does this PR introduce?
This PR adds Punjabi Language support for Novu.

Why this change was needed? (You can also link to an open issue here)
This PR fixes https://github.com/novuhq/novu/issues/1374

### CODE REVIEW

**Comment by ArmanChand** [comment]
@scopsy @davidsoderberg @ainouzgali Please review and approve. Also, please add the hacktoberfest-accepted label once it is approved. Thanks.

**Review by davidsoderberg — APPROVED** [review]

**Comment by ArmanChand** [comment]
@scopsy @davidsoderberg @ainouzgali Please review and approve. Also, please add the hacktoberfest-accepted label once it is approved. Thanks.

**Comment by ArmanChand** [comment]
@scopsy @davidsoderberg @ainouzgali  please merge it

**Review by p-fernandez — APPROVED** [review]
🌟

**Comment by davidsoderberg** [comment]
@ArmanChand please fix the conflicts :)

**Comment by ArmanChand** [comment]
@davidsoderberg , i dont find any merge conflicts. Please take a look and merge

**Comment by p-fernandez** [comment]
> @davidsoderberg , i dont find any merge conflicts. Please take a look and merge

I fixed them on your behalf.

**Pull request merged**
