### PR TITLE
fix: change streamToString to streamToBuffer in storage service

### LINKED ISSUE #2112: [NV-1265] 🐛 Bug Report: Email attachments are showing invalid
### 📜 Description

When sending emails with attachments, attachments are received as invalid in emails.

### 👟 Reproduction steps

1. Create a Notification
2. Trigger the notification with some `attachment`, I send attachment as,
```
{
  file: fs.readFileSync(path.join(__dirname, "img/facebook.png")),
  name: "facebook.png",
  mime: "image/png",
}
```
3. See the email received, the attachment will be `unprocessable (invalid)` to the system.

### 👍 Expected behavior

Attachments should be sent properly via email.

### 👎 Actual Behavior with Screenshots

How the attachment image looks in Ubuntu.
Screenshot from 2022-11-28 11-46-55

### 💻 Operating system

Linux

### 🤖 Node Version

16.15.1

### 📃 Provide any additional context for the Bug.

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

_No response_

<sub>[NV-1265](https://linear.app/novu/issue/NV-1265/🐛-bug-report-email-attachments-are-showing-invalid)</sub>

### PR DESCRIPTION
**Pull request by jainpawan21**
### What change does this PR introduce?
1. Change streamToString to streamToBuffer in the storage service

Few services support sending attachments as buffers and few as base64 strings. As `file` is already of `Buffer` type in `IAttachmentOptions` so returning buffer makes more sense so that as per the provider requirement, the buffer can be converted to base64

### Why was this change needed?

Closes #2112

### CODE REVIEW

**Comment by scopsy** [comment]
@jainpawan21 could you please take a look at the tests? Also, a small question, how did you know which provider need to receive base64 and which not? Did you had a chance to test it end to end with them?

**Comment by jainpawan21** [comment]
> @jainpawan21 could you please take a look at the tests? Also, a small question, how did you know which provider need to receive base64 and which not? Did you had a chance to test it end to end with them?

Yes Sure, I am looking into failing tests.
I tested with mailgun (buffer), sendinblue(base64), ses(buffer)

Working on testing all of providers.

**Comment by jainpawan21** [comment]
@scopsy Fixed failing test cases

**Review by p-fernandez — APPROVED** [review]
🌟

**Pull request merged**
