### PR TITLE
chore: add exportman + intial example configuration

### PR DESCRIPTION
**Pull request by webpro**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

This PR adds a tool to find unused files and exports, which helps with maintenance and keeping the project clean & tidy.

- **Why this change was needed?** (You can also link to an open issue here)

The project has some unused files and exports which could be cleaned up.

- **Other information**:

I think some examples make it more clear. Here's an example reporting only unused files:

```
❯ npx exportman --config exportman.json --cwd packages/notification-center --onlyFiles
--- UNUSED FILES (2)
src/lang.ts
src/shared/utils/applyToken.ts
```

This example reports unused files, exports, types and duplicate exports:

```
❯ npx exportman --config exportman.json --cwd apps/api
--- UNUSED FILES (9)
src/app/auth/framework/subscriber-route.decorator.ts
src/app/auth/services/auth.interface.ts
src/app/organization/dtos/get-invite.dto.ts
src/app/shared/constants.ts
src/app/shared/helpers/regex.service.ts
src/app/shared/services/cron/cron.service.ts
src/app/shared/services/mail/mail.service.ts
src/app/shared/services/sms/sms.service.ts
src/types/env.d.ts
--- UNUSED EXPORTS (7)
SubscriberPayloadDto        src/app/events/dtos/trigger-event-request.dto.ts
sanitizeHTML                src/app/message-template/shared/sanitizer.service.ts
MessageFilter               src/app/notification-template/usecases/create-notification-template/create-notification-template.command.ts
ChannelCTACommand           src/app/notification-template/usecases/create-notification-template/create-notification-template.command.ts
getFileExtensionFromPath    src/app/shared/services/helper/helper.service.ts
WS_SOCKET_QUEUE             src/app/shared/services/queue/queue.service.ts
IChannelCredentialsCommand  src/app/subscribers/usecases/update-subscriber-channel/update-subscriber-channel.command.ts
--- UNUSED TYPES (4)
IFilterVariables   src/app/events/usecases/trigger-event/message-filter.matcher.ts
Response           src/app/shared/framework/response.interceptor.ts
IDemoQueuePayload  src/app/shared/services/queue/queue.interface.ts
IFilePath          src/app/shared/services/storage/storage.service.ts
--- DUPLICATE EXPORTS (0)
N/A
```

Please note:

- I don't know the repo's conventions, so the configuration probably needs some additional tweaking.
- Exportman requires Node.js 16.17 or higher.
- See https://github.com/webpro/exportman for more details.

Happy to discuss any feedback or questions you may have! Your project caught my eye when I was looking for a nice workload to test exportman with, so I wanted to give something back by opening this pull request. Have a great day!

### CODE REVIEW

**Comment by p-fernandez** [comment]
@webpro how does this functionality work when analysing fully working functionalities that are not enabled in the codebase?
For example, you prepare a repository layer for an entity but it is not being used yet in any part of the domain as you have just developed. What's the workaround? My first thought would be to force to have tests for that exported function or class as there the export wouldn't be unused. But also comes with the drawback that you might not want to have unit tests for every export function/class you create.

**Comment by webpro** [comment]
> @webpro how does this functionality work when analysing fully working functionalities that are not enabled in the codebase? For example, you prepare a repository layer for an entity but it is not being used yet in any part of the domain as you have just developed. What's the workaround? My first thought would be to force to have tests for that exported function or class as there the export wouldn't be unused. But also comes with the drawback that you might not want to have unit tests for every export function/class you create.

If I understand correctly, this could be solved by adding a negation pattern for the duration of it not being part of the domain. When we take the `apps/api` example, you could add that pattern to the `filePatterns`, either as a specific file or the whole directory, so it will not be part of the project files and thus can't be reported as being unused:

```json
{
  "apps/api": {
    "entryFiles": ["src/main.ts"],
    "filePatterns": [
      "src/**/*.ts",
      "!**/*.e2e.ts",
      "!**/*.spec.ts",
      "!src/path/to/feature/**"
    ]
  }
}
```

Would that help?

By the way, in the example above, test files (`.e2e.ts` and `*.spec.ts`) are excluded from the project files. You could add another configuration file that does not exclude them to also scan the test files, e.g. `exportman.spec.json`:

```json
{
  "apps/api": {
    "entryFiles": ["src/**.spec.ts"],
    "filePatterns": [
      "src/**/*.ts",
      "!**/*.e2e.ts",
    ]
  }
}
```

As there might be unused test helpers, for instance. It just depends on your needs and how far you want to go with it.

**Comment by webpro** [comment]
There have been a few updates, so I updated the PR. One of the updates is an exit code for unused files, so exportman can become part of CI.

```
pnpm exec exportman --cwd apps/api --only files
src/app/auth/framework/subscriber-route.decorator.ts
src/app/auth/services/auth.interface.ts
src/app/organization/dtos/get-invite.dto.ts
src/app/shared/constants.ts
src/app/shared/helpers/regex.service.ts
src/app/shared/services/cron/cron.service.ts
src/app/shared/services/mail/mail.service.ts
src/app/shared/services/sms/sms.service.ts
src/types/env.d.ts
```

Feel free to read the updates docs @ https://github.com/webpro/exportman

**Comment by webpro** [comment]
Apologies to bother you again. Over the weekend I had an idea and it worked out pretty well. It even made me change the name of the project to "knip" (Dutch for "cut"), because the old name just didn't... cut it.

The tool now also finds (1) unused dependencies and (2) dependencies not listed in package.json. 

I think it's a nice addition for this project as well:

```
❯ pnpm exec knip --cwd apps/api
--- UNUSED FILES (9)
src/app/auth/framework/subscriber-route.decorator.ts
src/app/auth/services/auth.interface.ts
src/app/organization/dtos/get-invite.dto.ts
src/app/shared/constants.ts
src/app/shared/helpers/regex.service.ts
src/app/shared/services/cron/cron.service.ts
src/app/shared/services/mail/mail.service.ts
src/app/shared/services/sms/sms.service.ts
src/types/env.d.ts
--- UNUSED DEPENDENCIES (14)
@godaddy/terminus
@nestjs/axios
@nestjs/graphql
@sendgrid/mail
@types/analytics-node
@types/handlebars
@vendia/serverless-express
agenda
axios
cross-env
reflect-metadata
rimraf
swagger-ui-express
twilio
--- UNLISTED DEPENDENCIES (1)
mongoose  src/app/change/usecases/create-change.command.ts
```

The results are up for discussion, but upon some closer inspection we can see that indeed some of the unused dependencies can be removed. Or should perhaps be moved to `devDependencies`. The `mongoose` dependency I believe should be explicitly added to the local package's `package.json`.

Apologies for the perhaps chaotic pull request, I promise things are more stable now :)

**Comment by scopsy** [comment]
@webpro thank you so much for the PR, and I like the new `knip` name for it! I will definitely use it for my personal projects.

Due to our SOC2 and ISO compliance and observation period right now, adding a library in this early stage is problematic for us. We would love to see how it evolves and I will give it a try on my personal project. Once it will hit a bit more usage and community traction, we can consider integrating it again here. 

For now, I will close this pr as we won't be able to merge it due to the limitations above. 

Hope you will understand the reasoning behind it, and would love to contribute and chat about `knip` over discord!

**Comment by webpro** [comment]
Thanks, @scopsy! That's totally fine, best of luck with your project(s).

**Pull request closed without merging**
