### PR TITLE
Refactor web user preference design

### PR DESCRIPTION
**Pull request by djabarovgeorge**
PR of the new user preference design, please note that we still need to update the copy in the tab description.

@oba2311 Please let me know if you see any design flaws as there were last time (on a smaller screen - component lay on other components)

https://www.loom.com/share/c379a5afaf3f4f4c8a0e8e8e32d02786

### CODE REVIEW

**Comment by venarius** [comment]
Soo awesome!! 🔥
 
I have some food-for-thought if that's fine 😅 
1. The compact sidebar looks awesome. But I personally would not change between the compact sidebar and the normal one whilst switching tabs. It confuses the user and let's them think there's maybe a new menu now inside this tab. I would just double down on the new compact menu for all tabs and add the texts for the tabs as informative tooltips on hover.
2. I would remove the go back button on the workflow editor as there is now the menu and it's no longer a seperate window.
Screenshot 2022-08-24 014625

**Comment by djabarovgeorge** [comment]
Hey @venarius 
Thanks for taking the time to go through it! :) Regarding the point you raised.
1. could you clarify what you meant by 'double down on the new compact menu'?
2. I agree, I will consult with the team about it.

**Comment by venarius** [comment]
> 1. could you clarify what you meant by 'double down on the new compact menu'?
I think that we should just only use the new compact menu on all tabs instead of switching between the two variants when switching.

**Comment by djabarovgeorge** [comment]
@oba2311 What do you think about @venarius suggestions?

**Review by scopsy — APPROVED** [review]
@venarius I aggree with you on both bullets. We can remove the Go Back for now, regarding the other point on the consistency there, we will do another UX redesign soon with all the new learnings of the flow so will tackle it there and will include your thoughts as part of the design process.

**Pull request merged**
