### PR TITLE
Updated react-components.md by fixing minor comma errors

### PR DESCRIPTION
**Pull request by akshitagupta15june**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Updated react-components.md by fixing minor comma errors

- **Why was this change needed?** (You can also link to an open issue here)

proper use of commas in the document is required for good readability.

- **Other information**:

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
@davidsoderberg please review!

**Comment by akshitagupta15june** [comment]
@davidsoderberg @scopsy @p-fernandez  please review!

**Review by scopsy — APPROVED** [review]
Thank you so much for your contribution! Really appreciate it 🙏

**Comment by akshitagupta15june** [comment]
Happy to contribute

**Pull request merged**
