### PR TITLE
feat(api): Add template object to subscriber notification feed response

### LINKED ISSUE #3381: 🐛 Bug Report: template object missing in GET feed response
### 📜 Description

the API docs show an optional `template` object in response to the `GET feed` endpoint, but there is no way to specify it in the request and it is missing from the resopnse

### 👟 Reproduction steps

call the `GET feed` endpoint here: https://docs.novu.co/api/get-a-notification-feed-for-a-particular-subscriber/

### 👍 Expected behavior

expected to have the `template` object or at least be able to specify that we want it in the request

### 👎 Actual Behavior with Screenshots

it is missing from the response completely :( 

### 📃 Provide any additional context for the Bug.

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

### PR DESCRIPTION
**Pull request by peoray**
### What change does this PR introduce?
Fixes  #3381

### CODE REVIEW

**Review by p-fernandez — APPROVED** [review]
🌟 
Would be interesting to add an E2E test that checks this addition.

**Comment by jainpawan21** [comment]
@peoray please add test in this file
https://github.com/novuhq/novu/blob/next/apps/api/src/app/subscribers/e2e/get-notifications-feed.e2e.ts

**Comment by scopsy** [comment]
For some of the performance considerations here I would prefer if we return only the needed fields and not the whole template. @peoray maybe we can ask the issue opened about those?

**Comment by peoray** [comment]
@scopsy I have a question about that already. It is unanswered

**Comment by scopsy** [comment]
@peoray let's start with name, identifier and _id for now. Wdyt?

**Comment by scopsy** [comment]
Closing as stale 🙏

**Comment by peoray** [comment]
@scopsy how can this be reopened?

**Pull request closed without merging**
