### PR TITLE
fix: cypress json error

### PR DESCRIPTION
**Pull request by davidsoderberg**
### What change does this PR introduce?

Fix the failing cypress runs
https://github.com/cypress-io/cypress/issues/27555

### CODE REVIEW

**Comment by djabarovgeorge** [comment]
Interesting I wonder if it will fix the tests, i tried in the past to rollback to our previous version which was 12.3 i think and it did not help

**Review by djabarovgeorge — APPROVED** [review]
🥳

**Comment by djabarovgeorge** [comment]
i saw that all tests passed but one which was in progress, not sure what happened in the end there 😅

**Comment by scopsy** [comment]
@djabarovgeorge @davidsoderberg there is a suggestion that it was fixed in 13.2.0 from someone on GitHub. Worth trying

**Pull request closed without merging**
