### PR TITLE
fix: downgrade axios to v1.2.0

### LINKED ISSUE #2920: [NV-1780] 🐛 Bug Report: Bundled Version Stopped Working
### 📜 Description

I have been using the [Web Component (Bundled Version)](https://docs.novu.co/notification-center/web-component#bundled-version-preview) and realized that something broke. It was working at one time, when I first tried it out, however it seems to have randomly broken.

### 👟 Reproduction steps

1. Create simple HTML page
2. Attach Novu Web Component script in the head tag
3. Load the page to see the error in the console

Example code:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <script src="https://novu-web-component.netlify.app/index.js"></script>
  </head>
  <body>
    <notification-center-component
      style="display: inline-flex"
      application-identifier="hidden"
      subscriber-id="123"
    ></notification-center-component>
    <script>
      // here you can attach any callbacks, interact with the web component API
      let nc = document.getElementsByTagName('notification-center-component')[0];
      nc.onLoad = () => console.log('hello world!');
    </script>
  </body>
</html>
```

### 👍 Expected behavior

Notification Center should work, and I should see the component on the page.

### 👎 Actual Behavior with Screenshots

The Notification Center was never made, and gives a console error
image

### 📃 Provide any additional context for the Bug.

This was working a few weeks ago when I tried it, and just randomly broke the next time I checked.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1780](https://linear.app/novu/issue/NV-1780/🐛-bug-report-bundled-version-stopped-working)</sub>

### PR DESCRIPTION
**Pull request by BiswaViraj**
### What change does this PR introduce?
Closes #2920 

- Downgrades the Axios version inside `@novu/shared` package to `v1.2.0`
### Why was this change needed?

- Fixes the build fails of the bundled web component

### CODE REVIEW

**Comment by scopsy** [comment]
@BiswaViraj could you also add this to the renovate.json ignore so it won't try to update it again?

**Comment by BiswaViraj** [comment]
@scopsy 
Ok, adding it

**Comment by p-fernandez** [comment]
@BiswaViraj do you know what change of Axios is creating the problem? I wasn't able to find in our codebase or dependencies the constructor failing. 
Also looking for information about it seems it is a Node.js util so I am struggling to understand the relationship with the Axios package.

**Review by scopsy — APPROVED** [review]
Will merge this for now @p-fernandez @BiswaViraj you can continue the conversation with Pablo, just want to release a hot fix for customers for now

**Pull request merged**
