### PR TITLE
docs update

### PR DESCRIPTION
**Pull request by krishvsoni**
url added notification component of React, Vue and iframe

### What change does this PR introduce?
The PR displays the addition of URLs for the notification components provided by Novu in React, Vue, and iFrame.

An SDK is provided for all three libraries, but for the specific notification center, we don't have a direct URL. Therefore, I added it to the README file.

### Why was this change needed?
The change was necessary because the notification center's direct URL was not provided in the SDK for React, Vue, and iFrame. To ensure that users have access to this important component, I added its URL to the README file.

### Other information (Screenshots)
image

### CODE REVIEW

**Review by Cliftonz — APPROVED** [review]

**Comment by Cliftonz** [comment]
@krishvsoni Please ignore this being incorrectly labeled and closed, I was looking at the wrong tab.

Thank you for your contribution.

**Comment by krishvsoni** [comment]
> @krishvsoni Please ignore this being incorrectly labeled and closed, I was looking at the wrong tab.
> 
> Thank you for your contribution.

No worries, thanks for merging my PR.

**Comment by krishvsoni** [comment]
Please update my contribution on novu.co/contributors

**Comment by Cliftonz** [comment]
@krishvsoni this updates periodically itself (I guess 1 once a month but I am unsure). Your username should show up eventually.

**Comment by krishvsoni** [comment]
Okay thanks for clarifying 💯

**Pull request merged**
