### PR TITLE
feat: throttle refetch of notifications

### PR DESCRIPTION
**Pull request by venarius**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
fixes https://github.com/novuhq/novu/issues/1104

  This introduces a throtteling mechanism for the notifications refetch of the notification center.

- **Other information**:
  ### How this bug came to be:
  - ```apps/widget/cypress/e2e/notifications-list.spec.ts:31``` we create 3 additional notifications via cypress tasks
  - This triggers a new event on the server 3 times
  - The server sends 3 ```unseen_count_changed``` to the notification center via WebSocket
  - The notification center refetches the notification list on every ```unseen_count_changed``` event
  - Sometimes these api calls get out of order due to different response times from the server
  - The api call where there was 7 notifications came after the api call where there was 8 notifications
  - The user sees only 7 notifications but the unread count shows 8

  This throtteling mechanism fixes this problem as this can also be a real scenario for the user.

### CODE REVIEW

**Comment by djabarovgeorge** [comment]
Hey, @venarius  loved the solution!
Inspired by you may I suggest same approach but from another direction?

**Comment by venarius** [comment]
> Hey, @venarius loved the solution! Inspired by you may I suggest same approach but from another direction?

Sure, of course! 😊

**Comment by djabarovgeorge** [comment]
Well, I do not want to mess with the PR branch so I will just add it in the comment 😅

Due to the assumption that the problem is from refetch because of unseen_count_changed from the socket, could we add your fix to component NotificationsListTab useEffect? This way we won't need to manage the store id in the state.

image

Let me know what you think. @venarius

**Comment by venarius** [comment]
> Due to the assumption that the problem is from refetch because of unseen_count_changed from the socket, could we add your fix to component NotificationsListTab useEffect? This way we won't need to manage the store id in the state.

The problem is that there are still other places where refetch is being called. This would fix the issue of a bad state when the unseen count has changed. But what if at the same time the user would click on a notification? Then the refetch at ```NotificationsListTab.tsx:59``` could also be called at same exact time and then we would get these issues again. That's why I placed the throttle at the lowest possible location in the code right next to the actuall HTTP call. Wdyt?

**Comment by djabarovgeorge** [comment]
> The problem is that there are still other places where refetch is being called. This would fix the issue of a bad state when the unseen count has changed. But what if at the same time the user would click on a notification? Then the refetch at `NotificationsListTab.tsx:59` could also be called at same exact time and then we would get these issues again. That's why I placed the throttle at the lowest possible location in the code right next to the actuall HTTP call. Wdyt?

I think about two things :), 
1. First other cases are much rarer and, in my opinion, are neglected.
2. You are right about pressing the button issue, well if we are working with the socket, we could remove the 'refetch' on notification click because there will be a 'refetch' trigger because of the socket 'unseen_count' change. (or am I miss something)

Let me know what you think.

**Comment by venarius** [comment]
> 1. First other cases are much rarer and, in my opinion, are neglected.

This is true but nonetheless can still occur. That's why I wouldn't move this function up in the hierarchy.

> 2. You are right about pressing the button issue, well if we are working with the socket, we could remove the 'refetch' on notification click because there will be a 'refetch' trigger because of the socket 'unseen_count' change. (or am I miss something)

That would remove that refetch, true, but there is also one in ```NotificationsListTab.tsx:34``` so the issue could then still occur when the user switches tab I guess?

**Review by djabarovgeorge — APPROVED** [review]
After going over it again, your approach is more effective because we don't know what other behaviors will be added and what the user will do with the 'refetch' function.

**Pull request merged**
