### PR TITLE
feat: utilize entire screen height on workflow editor

### LINKED ISSUE #666: [NV-474] - Fit to screen's lentgh/size
## Why?

For some screens the bottom third is totally empty today. For larger screen it's very limiting the usable space.

## How?

Let's take advantage of that space by modifying the UI to fit the screen size. Making the screen fit inside the viewable port 100vh-(the existing header and spacing)

### Where?

In the apps/web project, to get the latest workflow editor, checkout from the `workflow` branch.

See:

\--\
Created via [Raycast](https://www.raycast.com?ref=signatureLinear)

### PR DESCRIPTION
**Pull request by Ian-Yy**
### What change does this PR introduce? 
This change will make workflow editor to utilize more screen height

### Why was this change needed?
Closes #666 

### Other information (Screenshots)

image

### CODE REVIEW

**Review by p-fernandez — APPROVED** [review]
I see no problems in this but what do you think about this improvement?
@LetItRock @ainouzgali

**Comment by LetItRock** [comment]
> I see no problems in this but what do you think about this improvement? @LetItRock @ainouzgali

@Ian-Yy @p-fernandez 
I think that we should improve this a little more if we want to utilize all the available space. The value `85vh` is not an ideal solution because it might look good on some screens, but won't do the job for ex. for bigger ones. 

What I would suggest is to do something like this: `calc(100vh - ${HEADER_HEIGHT}px - 60px)` instead, where the `HEADER_HEIGHT` is the constant extracted from the height property (65px) of `<Header` component in the `HeaderNav.tsx` file. The `60px` is a doubled padding around the `AppShell` unfortunately it comes from the Mantine.
This will solve the issue on bigger screens.

However it doesn't look good on the smallest ones that we support (1280x700), but it's a different story and it's the current state.

**Review by p-fernandez — CHANGES_REQUESTED** [review]
@Ian-Yy let's try to improve it based on @LetItRock comment 🙏🏻

**Comment by Ian-Yy** [comment]
Sorry for taking quite some time for this. Was quite occupied recently. Nevertheless, here's the changes as commented. Please let me know if anything else is needed.

**Review by p-fernandez — APPROVED** [review]
Looks good to me. @LetItRock is this change ok? If so, let's merge it. 🙂

**Comment by LetItRock** [comment]
> Looks good to me. @LetItRock is this change ok? If so, let's merge it. 🙂

@p-fernandez looks good to me ;) 

@Ian-Yy thanks a lot for your contribution! you rock! 🔥

**Pull request merged**
