### PR TITLE
Update providers list in readmes and docs

### PR DESCRIPTION
**Pull request by vrabe**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
docs update
- **Why was this change needed?** (You can also link to an open issue here)
Keep every providers lists up to date.
- **Other information**:
Some providers are not added: APNs, MailerSend, FireText. Should I add them?

### CODE REVIEW

**Review by scopsy — APPROVED** [review]
Thank you so much for your contribution! Really appreciate it 🙏

**Comment by vrabe** [comment]
Are APNs, MailerSend, and FireText ready to be put on?

**Comment by scopsy** [comment]
From next release we can add them :)

**Comment by vrabe** [comment]
So I reverted it. We can add them later!

**Pull request merged**
