### PR TITLE
i18n - Tamil Support

### LINKED ISSUE #1405: i18n - Tamil Support
## Why?

Recently novu introduced an easy way to add translations for the @novu/notification-center component interface. So we can either specify a translation object or pass a premade translation.

## How?

- Add a new translation file here: packages/notification-center/src/i18n/languages. You can follow the en.ts example.

- Add your translation import to the TRANSLATIONS object at packages/notification-center/src/i18n/lang.ts

- Add the language code to I18NLanguage type at lang.ts file.

I'd like to work on this issue.

### PR DESCRIPTION
**Pull request by abhilipsasahoo03**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature and Docs update: 
This PR adds Tamil Language support for Novu.

- **Why this change was needed?** (You can also link to an open issue here)
This PR fixes #1405

### CODE REVIEW

**Comment by abhilipsasahoo03** [comment]
@ainouzgali could you please take a look?

**Review by davidsoderberg — APPROVED** [review]

**Comment by abhilipsasahoo03** [comment]
@davidsoderberg @scopsy @ainouzgali I'd like this PR to be considered under Hacktoberfest contribution, so kindly add appropriate labels for it. Thank you!

**Review by p-fernandez — APPROVED** [review]
🌟

**Comment by abishekram** [comment]
I think these translations are not intended to solve the user issue. One translation has direct writing in Tamil spell same as "Settings". I hope these translations are not created just for hactoberfest.

**Comment by abhilipsasahoo03** [comment]
> I think these translations are not intended to solve the user issue. One translation has direct writing in Tamil spell same as "Settings". I hope these translations are not created just for hactoberfest. 

A lot of terms, particularly technology-related ones, have been borrowed into foreign languages directly. The system which allows me to send a message to you from my computer is known as email in English, and the same term is used in Odia because it was borrowed in from English. Same goes for "T.V" or "Computer" for any other technical jargon that may be difficult to translate or translates to something so fancy/ornamental that might confuse common users. "Settings" is also translated to a similarly pronounced word in Odia, Hindi and other languages to rather make stuff less confusing. That's the basic reason I could think of.

**Comment by abishekram** [comment]
Yes. Languages adopt new words. But I fear the problem we are trying to solve for translation and hactoberfest was not translate using google translate and creating PR. I am not suggesting, that you are doing. But in Tamil, we have words for TV, Computer and Settings.

For example, for "poweredBy", it was translated to மூலம் இயக்கப்படுகிறது . This is a directly translation (might be from google). They don't have any meaning in this context. Here the translation expects noun at first, not at after like English

 My concern would be creating PRs for supporting open source, instead of PR count or hactoberfest.

**Comment by abhilipsasahoo03** [comment]
I understand your concern. That was something that occured to me too. Even in Odia, "Powered By ____" has been translated to "____ ଦ୍ୱାରା ସଂଚାଳିତ /  ପରିଚାଳିତ" but that is the translation that comes the closest to accuracy when the subject (in the example "____")  is absent. I'm open to your suggestions regarding the same.

**Pull request merged**
