### PR TITLE
Fix typo in architecture.md

### PR DESCRIPTION
**Pull request by kVarunkk**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- This is a documentation update

- **Why this change was needed?** (You can also link to an open issue here)
- Typo and grammatical error were fixed

- **Other information**:
- architecture.md was updated

### CODE REVIEW

**Review by scopsy — APPROVED** [review]
Thank you!!!

**Comment by kVarunkk** [comment]
> Thank you!!!

Always :)
I'll work on more such typos and other errors in the documentation today!

**Comment by kVarunkk** [comment]
Hi @scopsy, if you don't mark my PRs as 'hacktoberfest-accepted', they won't be considered as a part of the hacktoberfest. Correct me if I'm wrong :) Because none of my PRs for novu have the tag I mentioned above.
Thanks!

**Comment by kVarunkk** [comment]
> Hi @kVarunkk, because we have the global topic of `hacktoberfest` on the repo, all merged PR's are counted and there is no need to mark them manually. Could you refer to the source that says that you must add them?

Hey @scopsy, I asked @eddiejaoude on twitter regarding this doubt of mine. Here's the [link](https://twitter.com/blckchan_vk/status/1577586782518284290?s=20&t=KOpxfI8YkdpM_7s1IAbFsw) to it.
Thanks!

**Pull request merged**
