### PR TITLE
Added a typescript file for the Georgian Language

### PR DESCRIPTION
**Pull request by Atharva1723**
### What change does this PR introduce?
Adding a typescript file for the Georgian Language

### Why was this change needed?
There was no support for the Georgian Language. So I created a typescript file for Georgian language

### CODE REVIEW

**Comment by Atharva1723** [comment]
@p-fernandez Can you please review this PR?

**Comment by Atharva1723** [comment]
@p-fernandez Can you please review this PR?

**Comment by p-fernandez** [comment]
@Atharva1723 do you speak georgian fluently? We favour to add translations by native people in the added languages.

**Comment by Atharva1723** [comment]
@p-fernandez No but a friend of mine does and I have referred to multiple translators and have cross-checked and I had also referred to the old Georgian typescript file ... You too can cross - verify

**Comment by p-fernandez** [comment]
> @p-fernandez No but a friend of mine does and I have referred to multiple translators and have cross-checked and I had also referred to the old Georgian typescript file ... You too can cross - verify

Could you ask your friend to also translate the `Powered By` translation? 🙏🏻

**Comment by Atharva1723** [comment]
> > @p-fernandez No but a friend of mine does and I have referred to multiple translators and have cross-checked and I had also referred to the old Georgian typescript file ... You too can cross - verify
> 
> Could you ask your friend to also translate the `Powered By` translation? 🙏🏻

Yes I have updated accordingly

**Review by p-fernandez — APPROVED** [review]
🌟

**Pull request merged**
