### PR TITLE
fix: fix double scroll bars in admin panel

### LINKED ISSUE #2326: 🐛 Bug Report: Double scroll bars in Admin Panel
### 📜 Description

Admin Panel layout are showing double scroll bars

### 👟 Reproduction steps

1. Go to any admin panel page
2. See at the page right the double scroll bars

### 👍 Expected behavior

It should be displayed single scroll bar?

### 👎 Actual Behavior with Screenshots

Captura de tela de 2022-12-19 22-44-30
Captura de tela de 2022-12-19 22-57-20

### 💻 Operating system

Linux

### 🤖 Node Version

16.18.1

### 📃 Provide any additional context for the Bug.

It happens in local env, not tested in web.novu.co.

Tested in Chrome, Brave and Firefox.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

### PR DESCRIPTION
**Pull request by caiopiassali**
### What change does this PR introduce? 

- Removes layout body fixed `height` property
- Adds `minHeight` property to layout body
- Removes side nav `flex` property

### Why was this change needed?

Closes #2326

### Other information (Screenshots)

Now single scroll bar are displayed:

image
image

### CODE REVIEW

**Comment by scopsy** [comment]
Hi @caiopiassali thank you for your contribution. One problem that this fix creates is when scrolling the top nav bar and left navbar are not fixed when scrolled (take a look at screenshot).

CleanShot 2022-12-21 at 10 28 33@2x

I think we should only avoid the outer scroll bar and leave the inpage one. What do you think?

**Comment by caiopiassali** [comment]
Hi @scopsy, I'm not sure if I understood what exactly is the outer scroll, but if you are talking about the page scroll I think is not possible to avoid it due the SideNav height in some screen sizes :thinking: 

What do you think about leaving the scroll in the container, like in the screenshot below?

Clipboard

With this approach the Header and SideNav will be fixed and the scrolling of the container will be clearer for the user.

**Comment by scopsy** [comment]
@caiopiassali I think this can work 🎉

**Comment by LetItRock** [comment]
@caiopiassali @scopsy 
I feel like all the scrolling issues could be solved by using the `position: sticky` for the header and side nav.
Check the video attached, and let me know what you think.


https://user-images.githubusercontent.com/2607232/209932528-52b9d1bf-f3ab-4afc-bd7c-68abae19fbb8.mov

File changes: 
HeaderNav --> Header
```
position: 'sticky',
top: 0
```

SideNav --> Navbar
```
position: 'sticky',
top: '65px',
height: 'max-content',
```

Also the header height could be moved to constant and reused.

**Comment by caiopiassali** [comment]
Thanks for the suggestion @LetItRock , I will try to do that

**Comment by LetItRock** [comment]
@caiopiassali please take a look into the failing tests, if any help needed let me know ;)

**Review by LetItRock — APPROVED** [review]

**Comment by LetItRock** [comment]
@caiopiassali thank you! 🚀

**Pull request merged**
