### PR TITLE
fix: fix wrong text in settings tab

### PR DESCRIPTION
**Pull request by MaximFedarau**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Full #1811 fix.

### CODE REVIEW

**Comment by MaximFedarau** [comment]
@scopsy, please, check if it solves the issue.

**Review by scopsy — APPROVED** [review]
Thank you so much for your contribution! Really appreciate it 🙏

**Comment by MaximFedarau** [comment]
@scopsy , @ainouzgali it shows tests errors, which are not connected with my changes🤨

**Comment by MaximFedarau** [comment]
@scopsy, @ainouzgali It fails tests, because I changed titles and tests are invalid => so tests should be changed.

**Comment by ainouzgali** [comment]
Hi @MaximFedarau the test is failing because in [the test of API keys](https://github.com/novuhq/novu/blob/main/apps/web/cypress/tests/settings.spec.ts#L19) it is searching for Api instead of your change to API - line 20.

**Comment by MaximFedarau** [comment]
Sure!

**Comment by MaximFedarau** [comment]
@ainouzgali, done.

**Comment by MaximFedarau** [comment]
@scopsy, @ainouzgali Everything passed!

**Pull request merged**
