### PR TITLE
ISSUE 101

### PR DESCRIPTION
**Pull request by dCOMMICS**

### CODE REVIEW

**Comment by ainouzgali** [comment]
Hi @dCOMMICS, what are you trying to do? I assume this was opened by mistake. 
Closing this. If you need help or clarification about our contribution rules feel free to reach out.

**Comment by dCOMMICS** [comment]
kindly any help will be appreciated am kinda new on this field.

**Comment by ainouzgali** [comment]
> kindly any help will be appreciated am kinda new on this field.

Sure. What is the problem? What are you trying to do?

**Comment by dCOMMICS** [comment]
how to opensource and how to contribute am a newbie

**Pull request closed without merging**
