### PR TITLE
feat(infra): add dev env setup script and plug it in jarvis

### PR DESCRIPTION
**Pull request by p-fernandez**
### What kind of change does this PR introduce? 

- [ ] Bug
- [X] Feature
- [ ] Docs
- [ ] Other(s)

A script that can be run individually or plugged by Jarvis to install the minimum tools a development environment system needs. So far run and tested in MacOSx environments. Potentially would work in Linux systems out of the box.

### Why was this change needed?

 

Creating an idempotent script that installs that based on the operative system could help to speed up the onboarding process. Also as @djabarovgeorge suggested, adding it to the Jarvis script could help collaborators to add all the tools needed to run the monolith that are missing in their system. Probably with some kind of interface and some of them skippable, as for example a collaborator wouldn't need to install AWS CLI to help us.

### Other information (Screenshots)

Screenshot 2022-11-07 at 14 43 30

### CODE REVIEW

**Comment by djabarovgeorge** [comment]
LOVE IT!

**Review by scopsy — APPROVED** [review]
Tried to run it locally with some already installed packages and it worked GREAT! We can merge this, and would be amazing to update the DOC regarding running novu locally as an optional way to install deps.

**Comment by p-fernandez** [comment]
> Tried to run it locally with some already installed packages and it worked GREAT! We can merge this, and would be amazing to update the DOC regarding running novu locally as an optional way to install deps.

Where in the docs should I add that information? Could you link the place? Thank you.

**Comment by scopsy** [comment]
@p-fernandez I think here would be perfect: https://docs.novu.co/community/run-locally

Under the Requirements section where the last comment about manually installing it with the link. We can just replace the link with a guide to jarvis. What do you think?

**Pull request merged**
